// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_suggestion.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAssignedWorkoutsInRange = `-- name: CountAssignedWorkoutsInRange :one
SELECT count(*) FROM assigned_workout
WHERE assignment_id = $1 AND scheduled_on IS NOT NULL
  AND scheduled_on BETWEEN $2 AND $3
`

type CountAssignedWorkoutsInRangeParams struct {
	AssignmentID  uuid.UUID  `json:"assignment_id"`
	ScheduledOn   *time.Time `json:"scheduled_on"`
	ScheduledOn_2 *time.Time `json:"scheduled_on_2"`
}

func (q *Queries) CountAssignedWorkoutsInRange(ctx context.Context, arg CountAssignedWorkoutsInRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignedWorkoutsInRange, arg.AssignmentID, arg.ScheduledOn, arg.ScheduledOn_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompletedHabitLogsSince = `-- name: CountCompletedHabitLogsSince :one
SELECT count(*) FROM habit_log hl
JOIN client_habit ch ON ch.id = hl.client_habit_id
WHERE hl.user_id = $1 AND hl.log_date >= $2 AND hl.is_completed = true AND ch.ended_on IS NULL
`

type CountCompletedHabitLogsSinceParams struct {
	UserID  uuid.UUID `json:"user_id"`
	LogDate time.Time `json:"log_date"`
}

func (q *Queries) CountCompletedHabitLogsSince(ctx context.Context, arg CountCompletedHabitLogsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedHabitLogsSince, arg.UserID, arg.LogDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompletedSessionsSince = `-- name: CountCompletedSessionsSince :one
SELECT count(*) FROM workout_session
WHERE user_id = $1 AND status = 'completed' AND started_at >= $2
`

type CountCompletedSessionsSinceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	StartedAt time.Time `json:"started_at"`
}

func (q *Queries) CountCompletedSessionsSince(ctx context.Context, arg CountCompletedSessionsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedSessionsSince, arg.UserID, arg.StartedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAISuggestion = `-- name: CreateAISuggestion :one
INSERT INTO ai_suggestion (
  org_id, client_user_id, coach_user_id, assignment_id, kind, payload,
  rationale, confidence, model, input_snapshot, expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, org_id, client_user_id, coach_user_id, assignment_id, kind, payload, rationale, confidence, model, input_snapshot, status, reviewed_by, reviewed_at, applied_at, expires_at, created_at
`

type CreateAISuggestionParams struct {
	OrgID         uuid.UUID      `json:"org_id"`
	ClientUserID  uuid.UUID      `json:"client_user_id"`
	CoachUserID   pgtype.UUID    `json:"coach_user_id"`
	AssignmentID  pgtype.UUID    `json:"assignment_id"`
	Kind          SuggestionKind `json:"kind"`
	Payload       []byte         `json:"payload"`
	Rationale     string         `json:"rationale"`
	Confidence    *float64       `json:"confidence"`
	Model         string         `json:"model"`
	InputSnapshot []byte         `json:"input_snapshot"`
	ExpiresAt     time.Time      `json:"expires_at"`
}

func (q *Queries) CreateAISuggestion(ctx context.Context, arg CreateAISuggestionParams) (AiSuggestion, error) {
	row := q.db.QueryRow(ctx, createAISuggestion,
		arg.OrgID,
		arg.ClientUserID,
		arg.CoachUserID,
		arg.AssignmentID,
		arg.Kind,
		arg.Payload,
		arg.Rationale,
		arg.Confidence,
		arg.Model,
		arg.InputSnapshot,
		arg.ExpiresAt,
	)
	var i AiSuggestion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientUserID,
		&i.CoachUserID,
		&i.AssignmentID,
		&i.Kind,
		&i.Payload,
		&i.Rationale,
		&i.Confidence,
		&i.Model,
		&i.InputSnapshot,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAISuggestionByID = `-- name: GetAISuggestionByID :one
SELECT id, org_id, client_user_id, coach_user_id, assignment_id, kind, payload, rationale, confidence, model, input_snapshot, status, reviewed_by, reviewed_at, applied_at, expires_at, created_at FROM ai_suggestion WHERE id = $1 AND org_id = $2
`

type GetAISuggestionByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetAISuggestionByID(ctx context.Context, arg GetAISuggestionByIDParams) (AiSuggestion, error) {
	row := q.db.QueryRow(ctx, getAISuggestionByID, arg.ID, arg.OrgID)
	var i AiSuggestion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientUserID,
		&i.CoachUserID,
		&i.AssignmentID,
		&i.Kind,
		&i.Payload,
		&i.Rationale,
		&i.Confidence,
		&i.Model,
		&i.InputSnapshot,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveAssignmentsForWorker = `-- name: ListActiveAssignmentsForWorker :many
SELECT a.id AS assignment_id, a.org_id, a.client_user_id, a.coach_user_id,
       u.full_name AS client_name
FROM assignment a
JOIN app_user u ON u.id = a.client_user_id
WHERE a.status = 'active'
`

type ListActiveAssignmentsForWorkerRow struct {
	AssignmentID uuid.UUID   `json:"assignment_id"`
	OrgID        uuid.UUID   `json:"org_id"`
	ClientUserID uuid.UUID   `json:"client_user_id"`
	CoachUserID  pgtype.UUID `json:"coach_user_id"`
	ClientName   string      `json:"client_name"`
}

func (q *Queries) ListActiveAssignmentsForWorker(ctx context.Context) ([]ListActiveAssignmentsForWorkerRow, error) {
	rows, err := q.db.Query(ctx, listActiveAssignmentsForWorker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAssignmentsForWorkerRow{}
	for rows.Next() {
		var i ListActiveAssignmentsForWorkerRow
		if err := rows.Scan(
			&i.AssignmentID,
			&i.OrgID,
			&i.ClientUserID,
			&i.CoachUserID,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSuggestionsForCoach = `-- name: ListPendingSuggestionsForCoach :many
SELECT s.id, s.org_id, s.client_user_id, s.coach_user_id, s.assignment_id, s.kind, s.payload, s.rationale, s.confidence, s.model, s.input_snapshot, s.status, s.reviewed_by, s.reviewed_at, s.applied_at, s.expires_at, s.created_at, u.full_name AS client_name
FROM ai_suggestion s
JOIN app_user u ON u.id = s.client_user_id
WHERE s.coach_user_id = $1 AND s.org_id = $2 AND s.status = 'pending'
ORDER BY s.created_at DESC
`

type ListPendingSuggestionsForCoachParams struct {
	CoachUserID pgtype.UUID `json:"coach_user_id"`
	OrgID       uuid.UUID   `json:"org_id"`
}

type ListPendingSuggestionsForCoachRow struct {
	ID            uuid.UUID        `json:"id"`
	OrgID         uuid.UUID        `json:"org_id"`
	ClientUserID  uuid.UUID        `json:"client_user_id"`
	CoachUserID   pgtype.UUID      `json:"coach_user_id"`
	AssignmentID  pgtype.UUID      `json:"assignment_id"`
	Kind          SuggestionKind   `json:"kind"`
	Payload       []byte           `json:"payload"`
	Rationale     string           `json:"rationale"`
	Confidence    *float64         `json:"confidence"`
	Model         string           `json:"model"`
	InputSnapshot []byte           `json:"input_snapshot"`
	Status        SuggestionStatus `json:"status"`
	ReviewedBy    pgtype.UUID      `json:"reviewed_by"`
	ReviewedAt    *time.Time       `json:"reviewed_at"`
	AppliedAt     *time.Time       `json:"applied_at"`
	ExpiresAt     time.Time        `json:"expires_at"`
	CreatedAt     time.Time        `json:"created_at"`
	ClientName    string           `json:"client_name"`
}

func (q *Queries) ListPendingSuggestionsForCoach(ctx context.Context, arg ListPendingSuggestionsForCoachParams) ([]ListPendingSuggestionsForCoachRow, error) {
	rows, err := q.db.Query(ctx, listPendingSuggestionsForCoach, arg.CoachUserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingSuggestionsForCoachRow{}
	for rows.Next() {
		var i ListPendingSuggestionsForCoachRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ClientUserID,
			&i.CoachUserID,
			&i.AssignmentID,
			&i.Kind,
			&i.Payload,
			&i.Rationale,
			&i.Confidence,
			&i.Model,
			&i.InputSnapshot,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.AppliedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentWorkingSets = `-- name: ListRecentWorkingSets :many
SELECT sl.exercise_id, e.name AS exercise_name, sl.weight_kg, sl.reps, sl.rpe, sl.performed_at
FROM set_log sl
JOIN exercise e ON e.id = sl.exercise_id
WHERE sl.user_id = $1 AND sl.type = 'working' AND sl.is_completed = true AND sl.performed_at >= $2
ORDER BY sl.performed_at ASC
LIMIT $3
`

type ListRecentWorkingSetsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	PerformedAt time.Time `json:"performed_at"`
	Limit       int32     `json:"limit"`
}

type ListRecentWorkingSetsRow struct {
	ExerciseID   uuid.UUID   `json:"exercise_id"`
	ExerciseName string      `json:"exercise_name"`
	WeightKg     *float64    `json:"weight_kg"`
	Reps         pgtype.Int2 `json:"reps"`
	Rpe          *float64    `json:"rpe"`
	PerformedAt  time.Time   `json:"performed_at"`
}

func (q *Queries) ListRecentWorkingSets(ctx context.Context, arg ListRecentWorkingSetsParams) ([]ListRecentWorkingSetsRow, error) {
	rows, err := q.db.Query(ctx, listRecentWorkingSets, arg.UserID, arg.PerformedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentWorkingSetsRow{}
	for rows.Next() {
		var i ListRecentWorkingSetsRow
		if err := rows.Scan(
			&i.ExerciseID,
			&i.ExerciseName,
			&i.WeightKg,
			&i.Reps,
			&i.Rpe,
			&i.PerformedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAISuggestionApplied = `-- name: MarkAISuggestionApplied :exec
UPDATE ai_suggestion SET applied_at = now() WHERE id = $1 AND org_id = $2
`

type MarkAISuggestionAppliedParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) MarkAISuggestionApplied(ctx context.Context, arg MarkAISuggestionAppliedParams) error {
	_, err := q.db.Exec(ctx, markAISuggestionApplied, arg.ID, arg.OrgID)
	return err
}

const reviewAISuggestion = `-- name: ReviewAISuggestion :one
UPDATE ai_suggestion
SET status = $3, reviewed_by = $4, reviewed_at = now()
WHERE id = $1 AND org_id = $2 AND status = 'pending'
RETURNING id, org_id, client_user_id, coach_user_id, assignment_id, kind, payload, rationale, confidence, model, input_snapshot, status, reviewed_by, reviewed_at, applied_at, expires_at, created_at
`

type ReviewAISuggestionParams struct {
	ID         uuid.UUID        `json:"id"`
	OrgID      uuid.UUID        `json:"org_id"`
	Status     SuggestionStatus `json:"status"`
	ReviewedBy pgtype.UUID      `json:"reviewed_by"`
}

func (q *Queries) ReviewAISuggestion(ctx context.Context, arg ReviewAISuggestionParams) (AiSuggestion, error) {
	row := q.db.QueryRow(ctx, reviewAISuggestion,
		arg.ID,
		arg.OrgID,
		arg.Status,
		arg.ReviewedBy,
	)
	var i AiSuggestion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientUserID,
		&i.CoachUserID,
		&i.AssignmentID,
		&i.Kind,
		&i.Payload,
		&i.Rationale,
		&i.Confidence,
		&i.Model,
		&i.InputSnapshot,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
