// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignment.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAssignment = `-- name: CancelAssignment :one
UPDATE assignment SET status = 'cancelled', end_date = CURRENT_DATE
WHERE id = $1 AND org_id = $2 AND status = 'active'
RETURNING id, org_id, program_id, client_user_id, coach_user_id, name, start_date, end_date, status, created_at, updated_at
`

type CancelAssignmentParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) CancelAssignment(ctx context.Context, arg CancelAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, cancelAssignment, arg.ID, arg.OrgID)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProgramID,
		&i.ClientUserID,
		&i.CoachUserID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAssignedExercise = `-- name: CreateAssignedExercise :one
INSERT INTO assigned_exercise (
  assigned_workout_id, exercise_id, order_index, superset_group, target_sets,
  target_reps_min, target_reps_max, target_rpe, target_weight_kg, rest_seconds,
  tempo, note, progression_rule_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, assigned_workout_id, exercise_id, order_index, superset_group, target_sets, target_reps_min, target_reps_max, target_rpe, target_weight_kg, rest_seconds, tempo, note, progression_rule_id
`

type CreateAssignedExerciseParams struct {
	AssignedWorkoutID uuid.UUID   `json:"assigned_workout_id"`
	ExerciseID        uuid.UUID   `json:"exercise_id"`
	OrderIndex        int16       `json:"order_index"`
	SupersetGroup     pgtype.Int2 `json:"superset_group"`
	TargetSets        int16       `json:"target_sets"`
	TargetRepsMin     pgtype.Int2 `json:"target_reps_min"`
	TargetRepsMax     pgtype.Int2 `json:"target_reps_max"`
	TargetRpe         *float64    `json:"target_rpe"`
	TargetWeightKg    *float64    `json:"target_weight_kg"`
	RestSeconds       int16       `json:"rest_seconds"`
	Tempo             pgtype.Text `json:"tempo"`
	Note              pgtype.Text `json:"note"`
	ProgressionRuleID pgtype.UUID `json:"progression_rule_id"`
}

func (q *Queries) CreateAssignedExercise(ctx context.Context, arg CreateAssignedExerciseParams) (AssignedExercise, error) {
	row := q.db.QueryRow(ctx, createAssignedExercise,
		arg.AssignedWorkoutID,
		arg.ExerciseID,
		arg.OrderIndex,
		arg.SupersetGroup,
		arg.TargetSets,
		arg.TargetRepsMin,
		arg.TargetRepsMax,
		arg.TargetRpe,
		arg.TargetWeightKg,
		arg.RestSeconds,
		arg.Tempo,
		arg.Note,
		arg.ProgressionRuleID,
	)
	var i AssignedExercise
	err := row.Scan(
		&i.ID,
		&i.AssignedWorkoutID,
		&i.ExerciseID,
		&i.OrderIndex,
		&i.SupersetGroup,
		&i.TargetSets,
		&i.TargetRepsMin,
		&i.TargetRepsMax,
		&i.TargetRpe,
		&i.TargetWeightKg,
		&i.RestSeconds,
		&i.Tempo,
		&i.Note,
		&i.ProgressionRuleID,
	)
	return i, err
}

const createAssignedWorkout = `-- name: CreateAssignedWorkout :one
INSERT INTO assigned_workout (assignment_id, source_workout_id, week_number, day_index, name, note, is_deload, scheduled_on, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending')
RETURNING id, assignment_id, source_workout_id, week_number, day_index, name, note, is_deload, scheduled_on, status
`

type CreateAssignedWorkoutParams struct {
	AssignmentID    uuid.UUID   `json:"assignment_id"`
	SourceWorkoutID pgtype.UUID `json:"source_workout_id"`
	WeekNumber      int16       `json:"week_number"`
	DayIndex        int16       `json:"day_index"`
	Name            string      `json:"name"`
	Note            pgtype.Text `json:"note"`
	IsDeload        bool        `json:"is_deload"`
	ScheduledOn     *time.Time  `json:"scheduled_on"`
}

func (q *Queries) CreateAssignedWorkout(ctx context.Context, arg CreateAssignedWorkoutParams) (AssignedWorkout, error) {
	row := q.db.QueryRow(ctx, createAssignedWorkout,
		arg.AssignmentID,
		arg.SourceWorkoutID,
		arg.WeekNumber,
		arg.DayIndex,
		arg.Name,
		arg.Note,
		arg.IsDeload,
		arg.ScheduledOn,
	)
	var i AssignedWorkout
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.SourceWorkoutID,
		&i.WeekNumber,
		&i.DayIndex,
		&i.Name,
		&i.Note,
		&i.IsDeload,
		&i.ScheduledOn,
		&i.Status,
	)
	return i, err
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignment (org_id, program_id, client_user_id, coach_user_id, name, start_date, status)
VALUES ($1, $2, $3, $4, $5, $6, 'active')
RETURNING id, org_id, program_id, client_user_id, coach_user_id, name, start_date, end_date, status, created_at, updated_at
`

type CreateAssignmentParams struct {
	OrgID        uuid.UUID   `json:"org_id"`
	ProgramID    pgtype.UUID `json:"program_id"`
	ClientUserID uuid.UUID   `json:"client_user_id"`
	CoachUserID  pgtype.UUID `json:"coach_user_id"`
	Name         string      `json:"name"`
	StartDate    time.Time   `json:"start_date"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.OrgID,
		arg.ProgramID,
		arg.ClientUserID,
		arg.CoachUserID,
		arg.Name,
		arg.StartDate,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProgramID,
		&i.ClientUserID,
		&i.CoachUserID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAssignmentByClient = `-- name: GetActiveAssignmentByClient :one
SELECT id, org_id, program_id, client_user_id, coach_user_id, name, start_date, end_date, status, created_at, updated_at FROM assignment WHERE client_user_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveAssignmentByClient(ctx context.Context, clientUserID uuid.UUID) (Assignment, error) {
	row := q.db.QueryRow(ctx, getActiveAssignmentByClient, clientUserID)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProgramID,
		&i.ClientUserID,
		&i.CoachUserID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT id, org_id, program_id, client_user_id, coach_user_id, name, start_date, end_date, status, created_at, updated_at FROM assignment WHERE id = $1
`

func (q *Queries) GetAssignmentByID(ctx context.Context, id uuid.UUID) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentByID, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProgramID,
		&i.ClientUserID,
		&i.CoachUserID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrgMembership = `-- name: GetOrgMembership :one
SELECT id, org_id, user_id, role, status, invited_by, joined_at, created_at, updated_at FROM membership WHERE org_id = $1 AND user_id = $2 AND status = 'active' LIMIT 1
`

type GetOrgMembershipParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOrgMembership(ctx context.Context, arg GetOrgMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getOrgMembership, arg.OrgID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignedExercises = `-- name: ListAssignedExercises :many
SELECT id, assigned_workout_id, exercise_id, order_index, superset_group, target_sets, target_reps_min, target_reps_max, target_rpe, target_weight_kg, rest_seconds, tempo, note, progression_rule_id FROM assigned_exercise WHERE assigned_workout_id = $1 ORDER BY order_index
`

func (q *Queries) ListAssignedExercises(ctx context.Context, assignedWorkoutID uuid.UUID) ([]AssignedExercise, error) {
	rows, err := q.db.Query(ctx, listAssignedExercises, assignedWorkoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssignedExercise{}
	for rows.Next() {
		var i AssignedExercise
		if err := rows.Scan(
			&i.ID,
			&i.AssignedWorkoutID,
			&i.ExerciseID,
			&i.OrderIndex,
			&i.SupersetGroup,
			&i.TargetSets,
			&i.TargetRepsMin,
			&i.TargetRepsMax,
			&i.TargetRpe,
			&i.TargetWeightKg,
			&i.RestSeconds,
			&i.Tempo,
			&i.Note,
			&i.ProgressionRuleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignedWorkouts = `-- name: ListAssignedWorkouts :many
SELECT id, assignment_id, source_workout_id, week_number, day_index, name, note, is_deload, scheduled_on, status FROM assigned_workout WHERE assignment_id = $1 ORDER BY week_number, day_index
`

func (q *Queries) ListAssignedWorkouts(ctx context.Context, assignmentID uuid.UUID) ([]AssignedWorkout, error) {
	rows, err := q.db.Query(ctx, listAssignedWorkouts, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssignedWorkout{}
	for rows.Next() {
		var i AssignedWorkout
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.SourceWorkoutID,
			&i.WeekNumber,
			&i.DayIndex,
			&i.Name,
			&i.Note,
			&i.IsDeload,
			&i.ScheduledOn,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
