// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (org_id, actor_user_id, action, entity_type, entity_id, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditLogParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    string      `json:"entity_id"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.OrgID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	return err
}
