// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coach.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const linkCoachClient = `-- name: LinkCoachClient :exec
INSERT INTO coach_client (org_id, coach_user_id, client_user_id)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, client_user_id) WHERE ended_at IS NULL
DO UPDATE SET coach_user_id = EXCLUDED.coach_user_id
`

type LinkCoachClientParams struct {
	OrgID        uuid.UUID `json:"org_id"`
	CoachUserID  uuid.UUID `json:"coach_user_id"`
	ClientUserID uuid.UUID `json:"client_user_id"`
}

func (q *Queries) LinkCoachClient(ctx context.Context, arg LinkCoachClientParams) error {
	_, err := q.db.Exec(ctx, linkCoachClient, arg.OrgID, arg.CoachUserID, arg.ClientUserID)
	return err
}

const listCoachClients = `-- name: ListCoachClients :many
SELECT
  cc.client_user_id,
  u.full_name,
  u.avatar_url,
  a.id AS assignment_id,
  a.name AS assignment_name,
  COALESCE((a.status)::text, '')::text AS assignment_status,
  COALESCE(
    (SELECT started_at FROM workout_session
      WHERE user_id = cc.client_user_id AND status = 'completed'
      ORDER BY started_at DESC LIMIT 1),
    'epoch'::timestamptz
  )::timestamptz AS last_session_at,
  COALESCE(st.current_count, 0)::int AS streak_days,
  COALESCE(pr.recent_prs, 0)::int AS recent_prs
FROM coach_client cc
JOIN app_user u ON u.id = cc.client_user_id
LEFT JOIN assignment a ON a.client_user_id = cc.client_user_id AND a.status = 'active'
LEFT JOIN user_streak st ON st.user_id = cc.client_user_id AND st.kind = 'workout'
LEFT JOIN LATERAL (
  SELECT count(*)::int AS recent_prs FROM personal_record
  WHERE user_id = cc.client_user_id AND achieved_at >= now() - interval '14 days'
) pr ON true
WHERE cc.org_id = $1 AND cc.coach_user_id = $2 AND cc.ended_at IS NULL
ORDER BY u.full_name
`

type ListCoachClientsParams struct {
	OrgID       uuid.UUID `json:"org_id"`
	CoachUserID uuid.UUID `json:"coach_user_id"`
}

type ListCoachClientsRow struct {
	ClientUserID     uuid.UUID   `json:"client_user_id"`
	FullName         string      `json:"full_name"`
	AvatarUrl        pgtype.Text `json:"avatar_url"`
	AssignmentID     pgtype.UUID `json:"assignment_id"`
	AssignmentName   pgtype.Text `json:"assignment_name"`
	AssignmentStatus string      `json:"assignment_status"`
	LastSessionAt    time.Time   `json:"last_session_at"`
	StreakDays       int32       `json:"streak_days"`
	RecentPrs        int32       `json:"recent_prs"`
}

func (q *Queries) ListCoachClients(ctx context.Context, arg ListCoachClientsParams) ([]ListCoachClientsRow, error) {
	rows, err := q.db.Query(ctx, listCoachClients, arg.OrgID, arg.CoachUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoachClientsRow{}
	for rows.Next() {
		var i ListCoachClientsRow
		if err := rows.Scan(
			&i.ClientUserID,
			&i.FullName,
			&i.AvatarUrl,
			&i.AssignmentID,
			&i.AssignmentName,
			&i.AssignmentStatus,
			&i.LastSessionAt,
			&i.StreakDays,
			&i.RecentPrs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
