// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_token.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :execrows
DELETE FROM device_token
WHERE token = $1 AND user_id = $2
`

type DeleteDeviceTokenParams struct {
	Token  string    `json:"token"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeviceToken, arg.Token, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDeviceTokensByUser = `-- name: ListDeviceTokensByUser :many
SELECT id, user_id, token, platform, last_seen_at, created_at FROM device_token
WHERE user_id = $1
ORDER BY last_seen_at DESC
`

func (q *Queries) ListDeviceTokensByUser(ctx context.Context, userID uuid.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO device_token (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE
  SET user_id = EXCLUDED.user_id,
      platform = EXCLUDED.platform,
      last_seen_at = now()
RETURNING id, user_id, token, platform, last_seen_at, created_at
`

type UpsertDeviceTokenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Token    string    `json:"token"`
	Platform string    `json:"platform"`
}

// El conflicto se resuelve por token, no por (user_id, token): el token es
// UNIQUE global y FCM devuelve el mismo cuando otro usuario entra en el
// mismo telefono, asi que la fila tiene que cambiar de dueno.
func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken, arg.UserID, arg.Token, arg.Platform)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}
