// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercise.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercise (
  org_id, slug, name, description, instructions, pattern, mechanic,
  primary_muscle, secondary_muscles, equipment, difficulty, tracking,
  is_unilateral, video_url, thumbnail_url, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id, org_id, slug, name, description, instructions, pattern, mechanic, primary_muscle, secondary_muscles, equipment, difficulty, tracking, is_unilateral, video_url, thumbnail_url, created_by, is_active, created_at, updated_at
`

type CreateExerciseParams struct {
	OrgID            pgtype.UUID      `json:"org_id"`
	Slug             string           `json:"slug"`
	Name             string           `json:"name"`
	Description      pgtype.Text      `json:"description"`
	Instructions     []string         `json:"instructions"`
	Pattern          MovementPattern  `json:"pattern"`
	Mechanic         ExerciseMechanic `json:"mechanic"`
	PrimaryMuscle    string           `json:"primary_muscle"`
	SecondaryMuscles []string         `json:"secondary_muscles"`
	Equipment        []string         `json:"equipment"`
	Difficulty       ExperienceLevel  `json:"difficulty"`
	Tracking         TrackingMode     `json:"tracking"`
	IsUnilateral     bool             `json:"is_unilateral"`
	VideoUrl         pgtype.Text      `json:"video_url"`
	ThumbnailUrl     pgtype.Text      `json:"thumbnail_url"`
	CreatedBy        pgtype.UUID      `json:"created_by"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise,
		arg.OrgID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Instructions,
		arg.Pattern,
		arg.Mechanic,
		arg.PrimaryMuscle,
		arg.SecondaryMuscles,
		arg.Equipment,
		arg.Difficulty,
		arg.Tracking,
		arg.IsUnilateral,
		arg.VideoUrl,
		arg.ThumbnailUrl,
		arg.CreatedBy,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Pattern,
		&i.Mechanic,
		&i.PrimaryMuscle,
		&i.SecondaryMuscles,
		&i.Equipment,
		&i.Difficulty,
		&i.Tracking,
		&i.IsUnilateral,
		&i.VideoUrl,
		&i.ThumbnailUrl,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateExercise = `-- name: DeactivateExercise :exec
UPDATE exercise SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateExercise(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateExercise, id)
	return err
}

const getExerciseByID = `-- name: GetExerciseByID :one
SELECT id, org_id, slug, name, description, instructions, pattern, mechanic, primary_muscle, secondary_muscles, equipment, difficulty, tracking, is_unilateral, video_url, thumbnail_url, created_by, is_active, created_at, updated_at FROM exercise WHERE id = $1 AND is_active = true
`

func (q *Queries) GetExerciseByID(ctx context.Context, id uuid.UUID) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExerciseByID, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Pattern,
		&i.Mechanic,
		&i.PrimaryMuscle,
		&i.SecondaryMuscles,
		&i.Equipment,
		&i.Difficulty,
		&i.Tracking,
		&i.IsUnilateral,
		&i.VideoUrl,
		&i.ThumbnailUrl,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExercises = `-- name: ListExercises :many
SELECT id, org_id, slug, name, description, instructions, pattern, mechanic, primary_muscle, secondary_muscles, equipment, difficulty, tracking, is_unilateral, video_url, thumbnail_url, created_by, is_active, created_at, updated_at FROM exercise
WHERE is_active = true
  AND (org_id IS NULL OR org_id = $1)
  AND ($2::movement_pattern IS NULL OR pattern = $2)
  AND ($3::text IS NULL OR primary_muscle = $3)
ORDER BY name
LIMIT $5 OFFSET $4
`

type ListExercisesParams struct {
	OrgID       pgtype.UUID         `json:"org_id"`
	Pattern     NullMovementPattern `json:"pattern"`
	Muscle      pgtype.Text         `json:"muscle"`
	OffsetCount int32               `json:"offset_count"`
	LimitCount  int32               `json:"limit_count"`
}

func (q *Queries) ListExercises(ctx context.Context, arg ListExercisesParams) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercises,
		arg.OrgID,
		arg.Pattern,
		arg.Muscle,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.Pattern,
			&i.Mechanic,
			&i.PrimaryMuscle,
			&i.SecondaryMuscles,
			&i.Equipment,
			&i.Difficulty,
			&i.Tracking,
			&i.IsUnilateral,
			&i.VideoUrl,
			&i.ThumbnailUrl,
			&i.CreatedBy,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExercise = `-- name: UpdateExercise :one
UPDATE exercise SET
  name = $2, description = $3, instructions = $4, pattern = $5,
  mechanic = $6, primary_muscle = $7, secondary_muscles = $8,
  equipment = $9, difficulty = $10, tracking = $11, is_unilateral = $12,
  video_url = $13, thumbnail_url = $14
WHERE id = $1
RETURNING id, org_id, slug, name, description, instructions, pattern, mechanic, primary_muscle, secondary_muscles, equipment, difficulty, tracking, is_unilateral, video_url, thumbnail_url, created_by, is_active, created_at, updated_at
`

type UpdateExerciseParams struct {
	ID               uuid.UUID        `json:"id"`
	Name             string           `json:"name"`
	Description      pgtype.Text      `json:"description"`
	Instructions     []string         `json:"instructions"`
	Pattern          MovementPattern  `json:"pattern"`
	Mechanic         ExerciseMechanic `json:"mechanic"`
	PrimaryMuscle    string           `json:"primary_muscle"`
	SecondaryMuscles []string         `json:"secondary_muscles"`
	Equipment        []string         `json:"equipment"`
	Difficulty       ExperienceLevel  `json:"difficulty"`
	Tracking         TrackingMode     `json:"tracking"`
	IsUnilateral     bool             `json:"is_unilateral"`
	VideoUrl         pgtype.Text      `json:"video_url"`
	ThumbnailUrl     pgtype.Text      `json:"thumbnail_url"`
}

func (q *Queries) UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, updateExercise,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Instructions,
		arg.Pattern,
		arg.Mechanic,
		arg.PrimaryMuscle,
		arg.SecondaryMuscles,
		arg.Equipment,
		arg.Difficulty,
		arg.Tracking,
		arg.IsUnilateral,
		arg.VideoUrl,
		arg.ThumbnailUrl,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Pattern,
		&i.Mechanic,
		&i.PrimaryMuscle,
		&i.SecondaryMuscles,
		&i.Equipment,
		&i.Difficulty,
		&i.Tracking,
		&i.IsUnilateral,
		&i.VideoUrl,
		&i.ThumbnailUrl,
		&i.CreatedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
