// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gamification.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createXPEvent = `-- name: CreateXPEvent :one
INSERT INTO xp_event (user_id, source, points, reference_id) VALUES ($1, $2, $3, $4) RETURNING id, user_id, source, points, reference_id, created_at
`

type CreateXPEventParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Source      XpSource    `json:"source"`
	Points      int32       `json:"points"`
	ReferenceID pgtype.Text `json:"reference_id"`
}

func (q *Queries) CreateXPEvent(ctx context.Context, arg CreateXPEventParams) (XpEvent, error) {
	row := q.db.QueryRow(ctx, createXPEvent,
		arg.UserID,
		arg.Source,
		arg.Points,
		arg.ReferenceID,
	)
	var i XpEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.Points,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAchievement = `-- name: GetUserAchievement :one
SELECT user_id, achievement_id, progress, earned_at FROM user_achievement WHERE user_id = $1 AND achievement_id = $2
`

type GetUserAchievementParams struct {
	UserID        uuid.UUID `json:"user_id"`
	AchievementID uuid.UUID `json:"achievement_id"`
}

func (q *Queries) GetUserAchievement(ctx context.Context, arg GetUserAchievementParams) (UserAchievement, error) {
	row := q.db.QueryRow(ctx, getUserAchievement, arg.UserID, arg.AchievementID)
	var i UserAchievement
	err := row.Scan(
		&i.UserID,
		&i.AchievementID,
		&i.Progress,
		&i.EarnedAt,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT user_id, total_xp, level, total_sessions, total_volume_kg, updated_at FROM user_stats WHERE user_id = $1
`

func (q *Queries) GetUserStats(ctx context.Context, userID uuid.UUID) (UserStat, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.TotalXp,
		&i.Level,
		&i.TotalSessions,
		&i.TotalVolumeKg,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserStatsForUpdate = `-- name: GetUserStatsForUpdate :one
SELECT user_id, total_xp, level, total_sessions, total_volume_kg, updated_at FROM user_stats WHERE user_id = $1 FOR UPDATE
`

// Variante con lock de fila para el read-modify-write de ApplyStatsDelta.
// La version sin lock se usa en las lecturas de solo lectura (/me/stats),
// que no deberian bloquear a nadie.
func (q *Queries) GetUserStatsForUpdate(ctx context.Context, userID uuid.UUID) (UserStat, error) {
	row := q.db.QueryRow(ctx, getUserStatsForUpdate, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.TotalXp,
		&i.Level,
		&i.TotalSessions,
		&i.TotalVolumeKg,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserStreak = `-- name: GetUserStreak :one
SELECT user_id, kind, current_count, longest_count, last_active_on, freezes_left FROM user_streak WHERE user_id = $1 AND kind = $2
`

type GetUserStreakParams struct {
	UserID uuid.UUID  `json:"user_id"`
	Kind   StreakKind `json:"kind"`
}

func (q *Queries) GetUserStreak(ctx context.Context, arg GetUserStreakParams) (UserStreak, error) {
	row := q.db.QueryRow(ctx, getUserStreak, arg.UserID, arg.Kind)
	var i UserStreak
	err := row.Scan(
		&i.UserID,
		&i.Kind,
		&i.CurrentCount,
		&i.LongestCount,
		&i.LastActiveOn,
		&i.FreezesLeft,
	)
	return i, err
}

const getUserStreakForUpdate = `-- name: GetUserStreakForUpdate :one
SELECT user_id, kind, current_count, longest_count, last_active_on, freezes_left FROM user_streak WHERE user_id = $1 AND kind = $2 FOR UPDATE
`

type GetUserStreakForUpdateParams struct {
	UserID uuid.UUID  `json:"user_id"`
	Kind   StreakKind `json:"kind"`
}

func (q *Queries) GetUserStreakForUpdate(ctx context.Context, arg GetUserStreakForUpdateParams) (UserStreak, error) {
	row := q.db.QueryRow(ctx, getUserStreakForUpdate, arg.UserID, arg.Kind)
	var i UserStreak
	err := row.Scan(
		&i.UserID,
		&i.Kind,
		&i.CurrentCount,
		&i.LongestCount,
		&i.LastActiveOn,
		&i.FreezesLeft,
	)
	return i, err
}

const listAchievements = `-- name: ListAchievements :many
SELECT id, code, name, description, icon, tier, xp_reward, criteria FROM achievement ORDER BY tier, name
`

func (q *Queries) ListAchievements(ctx context.Context) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, listAchievements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Achievement{}
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Tier,
			&i.XpReward,
			&i.Criteria,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAchievements = `-- name: ListUserAchievements :many
SELECT ua.user_id, ua.achievement_id, ua.progress, ua.earned_at,
       a.code, a.name, a.description, a.icon, a.tier, a.xp_reward
FROM user_achievement ua
JOIN achievement a ON a.id = ua.achievement_id
WHERE ua.user_id = $1
ORDER BY a.tier, a.name
`

type ListUserAchievementsRow struct {
	UserID        uuid.UUID  `json:"user_id"`
	AchievementID uuid.UUID  `json:"achievement_id"`
	Progress      float64    `json:"progress"`
	EarnedAt      *time.Time `json:"earned_at"`
	Code          string     `json:"code"`
	Name          string     `json:"name"`
	Description   string     `json:"description"`
	Icon          string     `json:"icon"`
	Tier          int16      `json:"tier"`
	XpReward      int32      `json:"xp_reward"`
}

func (q *Queries) ListUserAchievements(ctx context.Context, userID uuid.UUID) ([]ListUserAchievementsRow, error) {
	rows, err := q.db.Query(ctx, listUserAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAchievementsRow{}
	for rows.Next() {
		var i ListUserAchievementsRow
		if err := rows.Scan(
			&i.UserID,
			&i.AchievementID,
			&i.Progress,
			&i.EarnedAt,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Tier,
			&i.XpReward,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserStreaks = `-- name: ListUserStreaks :many
SELECT user_id, kind, current_count, longest_count, last_active_on, freezes_left FROM user_streak WHERE user_id = $1
`

func (q *Queries) ListUserStreaks(ctx context.Context, userID uuid.UUID) ([]UserStreak, error) {
	rows, err := q.db.Query(ctx, listUserStreaks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserStreak{}
	for rows.Next() {
		var i UserStreak
		if err := rows.Scan(
			&i.UserID,
			&i.Kind,
			&i.CurrentCount,
			&i.LongestCount,
			&i.LastActiveOn,
			&i.FreezesLeft,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserAchievement = `-- name: UpsertUserAchievement :one
INSERT INTO user_achievement (user_id, achievement_id, progress, earned_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, achievement_id) DO UPDATE SET
  progress = EXCLUDED.progress,
  earned_at = COALESCE(user_achievement.earned_at, EXCLUDED.earned_at)
RETURNING user_id, achievement_id, progress, earned_at
`

type UpsertUserAchievementParams struct {
	UserID        uuid.UUID  `json:"user_id"`
	AchievementID uuid.UUID  `json:"achievement_id"`
	Progress      float64    `json:"progress"`
	EarnedAt      *time.Time `json:"earned_at"`
}

func (q *Queries) UpsertUserAchievement(ctx context.Context, arg UpsertUserAchievementParams) (UserAchievement, error) {
	row := q.db.QueryRow(ctx, upsertUserAchievement,
		arg.UserID,
		arg.AchievementID,
		arg.Progress,
		arg.EarnedAt,
	)
	var i UserAchievement
	err := row.Scan(
		&i.UserID,
		&i.AchievementID,
		&i.Progress,
		&i.EarnedAt,
	)
	return i, err
}

const upsertUserStats = `-- name: UpsertUserStats :one
INSERT INTO user_stats (user_id, total_xp, level, total_sessions, total_volume_kg)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
  total_xp = EXCLUDED.total_xp, level = EXCLUDED.level, total_sessions = EXCLUDED.total_sessions,
  total_volume_kg = EXCLUDED.total_volume_kg, updated_at = now()
RETURNING user_id, total_xp, level, total_sessions, total_volume_kg, updated_at
`

type UpsertUserStatsParams struct {
	UserID        uuid.UUID `json:"user_id"`
	TotalXp       int32     `json:"total_xp"`
	Level         int16     `json:"level"`
	TotalSessions int32     `json:"total_sessions"`
	TotalVolumeKg float64   `json:"total_volume_kg"`
}

func (q *Queries) UpsertUserStats(ctx context.Context, arg UpsertUserStatsParams) (UserStat, error) {
	row := q.db.QueryRow(ctx, upsertUserStats,
		arg.UserID,
		arg.TotalXp,
		arg.Level,
		arg.TotalSessions,
		arg.TotalVolumeKg,
	)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.TotalXp,
		&i.Level,
		&i.TotalSessions,
		&i.TotalVolumeKg,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserStreak = `-- name: UpsertUserStreak :one
INSERT INTO user_streak (user_id, kind, current_count, longest_count, last_active_on)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, kind) DO UPDATE SET
  current_count = EXCLUDED.current_count, longest_count = EXCLUDED.longest_count,
  last_active_on = EXCLUDED.last_active_on
RETURNING user_id, kind, current_count, longest_count, last_active_on, freezes_left
`

type UpsertUserStreakParams struct {
	UserID       uuid.UUID  `json:"user_id"`
	Kind         StreakKind `json:"kind"`
	CurrentCount int32      `json:"current_count"`
	LongestCount int32      `json:"longest_count"`
	LastActiveOn *time.Time `json:"last_active_on"`
}

func (q *Queries) UpsertUserStreak(ctx context.Context, arg UpsertUserStreakParams) (UserStreak, error) {
	row := q.db.QueryRow(ctx, upsertUserStreak,
		arg.UserID,
		arg.Kind,
		arg.CurrentCount,
		arg.LongestCount,
		arg.LastActiveOn,
	)
	var i UserStreak
	err := row.Scan(
		&i.UserID,
		&i.Kind,
		&i.CurrentCount,
		&i.LongestCount,
		&i.LastActiveOn,
		&i.FreezesLeft,
	)
	return i, err
}
