// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: habit.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveHabitsForUser = `-- name: CountActiveHabitsForUser :one
SELECT count(*) FROM client_habit WHERE user_id = $1 AND ended_on IS NULL
`

func (q *Queries) CountActiveHabitsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveHabitsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompletedHabitLogsForDate = `-- name: CountCompletedHabitLogsForDate :one
SELECT count(*) FROM habit_log hl
JOIN client_habit ch ON ch.id = hl.client_habit_id
WHERE hl.user_id = $1 AND hl.log_date = $2 AND hl.is_completed = true AND ch.ended_on IS NULL
`

type CountCompletedHabitLogsForDateParams struct {
	UserID  uuid.UUID `json:"user_id"`
	LogDate time.Time `json:"log_date"`
}

func (q *Queries) CountCompletedHabitLogsForDate(ctx context.Context, arg CountCompletedHabitLogsForDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedHabitLogsForDate, arg.UserID, arg.LogDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveClientHabit = `-- name: GetActiveClientHabit :one
SELECT id, user_id, habit_id, assigned_by, target_value, frequency, days_of_week, reminder_time, started_on, ended_on FROM client_habit WHERE user_id = $1 AND habit_id = $2 AND ended_on IS NULL
`

type GetActiveClientHabitParams struct {
	UserID  uuid.UUID `json:"user_id"`
	HabitID uuid.UUID `json:"habit_id"`
}

func (q *Queries) GetActiveClientHabit(ctx context.Context, arg GetActiveClientHabitParams) (ClientHabit, error) {
	row := q.db.QueryRow(ctx, getActiveClientHabit, arg.UserID, arg.HabitID)
	var i ClientHabit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HabitID,
		&i.AssignedBy,
		&i.TargetValue,
		&i.Frequency,
		&i.DaysOfWeek,
		&i.ReminderTime,
		&i.StartedOn,
		&i.EndedOn,
	)
	return i, err
}

const getHabitByID = `-- name: GetHabitByID :one
SELECT id, org_id, slug, name, icon, unit, default_target, is_system, created_at FROM habit WHERE id = $1
`

func (q *Queries) GetHabitByID(ctx context.Context, id uuid.UUID) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabitByID, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.Icon,
		&i.Unit,
		&i.DefaultTarget,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listHabitLogsForDate = `-- name: ListHabitLogsForDate :many
SELECT id, client_local_id, client_habit_id, user_id, log_date, value, is_completed, logged_at FROM habit_log WHERE user_id = $1 AND log_date = $2
`

type ListHabitLogsForDateParams struct {
	UserID  uuid.UUID `json:"user_id"`
	LogDate time.Time `json:"log_date"`
}

func (q *Queries) ListHabitLogsForDate(ctx context.Context, arg ListHabitLogsForDateParams) ([]HabitLog, error) {
	rows, err := q.db.Query(ctx, listHabitLogsForDate, arg.UserID, arg.LogDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HabitLog{}
	for rows.Next() {
		var i HabitLog
		if err := rows.Scan(
			&i.ID,
			&i.ClientLocalID,
			&i.ClientHabitID,
			&i.UserID,
			&i.LogDate,
			&i.Value,
			&i.IsCompleted,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabits = `-- name: ListHabits :many
SELECT id, org_id, slug, name, icon, unit, default_target, is_system, created_at FROM habit
WHERE org_id IS NULL OR org_id = $1
ORDER BY is_system DESC, name
`

func (q *Queries) ListHabits(ctx context.Context, orgID pgtype.UUID) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listHabits, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Habit{}
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Icon,
			&i.Unit,
			&i.DefaultTarget,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyHabits = `-- name: ListMyHabits :many
SELECT ch.id, ch.user_id, ch.habit_id, ch.target_value, ch.frequency, ch.days_of_week,
       ch.started_on, ch.ended_on, h.name AS habit_name, h.icon AS habit_icon, h.unit AS habit_unit
FROM client_habit ch
JOIN habit h ON h.id = ch.habit_id
WHERE ch.user_id = $1 AND ch.ended_on IS NULL
ORDER BY h.name
`

type ListMyHabitsRow struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	HabitID     uuid.UUID      `json:"habit_id"`
	TargetValue *float64       `json:"target_value"`
	Frequency   HabitFrequency `json:"frequency"`
	DaysOfWeek  []int16        `json:"days_of_week"`
	StartedOn   time.Time      `json:"started_on"`
	EndedOn     *time.Time     `json:"ended_on"`
	HabitName   string         `json:"habit_name"`
	HabitIcon   string         `json:"habit_icon"`
	HabitUnit   HabitUnit      `json:"habit_unit"`
}

func (q *Queries) ListMyHabits(ctx context.Context, userID uuid.UUID) ([]ListMyHabitsRow, error) {
	rows, err := q.db.Query(ctx, listMyHabits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyHabitsRow{}
	for rows.Next() {
		var i ListMyHabitsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.HabitID,
			&i.TargetValue,
			&i.Frequency,
			&i.DaysOfWeek,
			&i.StartedOn,
			&i.EndedOn,
			&i.HabitName,
			&i.HabitIcon,
			&i.HabitUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribeHabit = `-- name: SubscribeHabit :one
INSERT INTO client_habit (user_id, habit_id, assigned_by, target_value, frequency, days_of_week)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, habit_id, assigned_by, target_value, frequency, days_of_week, reminder_time, started_on, ended_on
`

type SubscribeHabitParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	HabitID     uuid.UUID      `json:"habit_id"`
	AssignedBy  pgtype.UUID    `json:"assigned_by"`
	TargetValue *float64       `json:"target_value"`
	Frequency   HabitFrequency `json:"frequency"`
	DaysOfWeek  []int16        `json:"days_of_week"`
}

func (q *Queries) SubscribeHabit(ctx context.Context, arg SubscribeHabitParams) (ClientHabit, error) {
	row := q.db.QueryRow(ctx, subscribeHabit,
		arg.UserID,
		arg.HabitID,
		arg.AssignedBy,
		arg.TargetValue,
		arg.Frequency,
		arg.DaysOfWeek,
	)
	var i ClientHabit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.HabitID,
		&i.AssignedBy,
		&i.TargetValue,
		&i.Frequency,
		&i.DaysOfWeek,
		&i.ReminderTime,
		&i.StartedOn,
		&i.EndedOn,
	)
	return i, err
}

const unsubscribeHabit = `-- name: UnsubscribeHabit :exec
UPDATE client_habit SET ended_on = CURRENT_DATE WHERE id = $1 AND user_id = $2
`

type UnsubscribeHabitParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnsubscribeHabit(ctx context.Context, arg UnsubscribeHabitParams) error {
	_, err := q.db.Exec(ctx, unsubscribeHabit, arg.ID, arg.UserID)
	return err
}

const upsertHabitLog = `-- name: UpsertHabitLog :one
INSERT INTO habit_log (client_local_id, client_habit_id, user_id, log_date, value, is_completed)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, client_local_id) DO UPDATE SET
  value = EXCLUDED.value, is_completed = EXCLUDED.is_completed
RETURNING id, client_local_id, client_habit_id, user_id, log_date, value, is_completed, logged_at
`

type UpsertHabitLogParams struct {
	ClientLocalID uuid.UUID `json:"client_local_id"`
	ClientHabitID uuid.UUID `json:"client_habit_id"`
	UserID        uuid.UUID `json:"user_id"`
	LogDate       time.Time `json:"log_date"`
	Value         float64   `json:"value"`
	IsCompleted   bool      `json:"is_completed"`
}

func (q *Queries) UpsertHabitLog(ctx context.Context, arg UpsertHabitLogParams) (HabitLog, error) {
	row := q.db.QueryRow(ctx, upsertHabitLog,
		arg.ClientLocalID,
		arg.ClientHabitID,
		arg.UserID,
		arg.LogDate,
		arg.Value,
		arg.IsCompleted,
	)
	var i HabitLog
	err := row.Scan(
		&i.ID,
		&i.ClientLocalID,
		&i.ClientHabitID,
		&i.UserID,
		&i.LogDate,
		&i.Value,
		&i.IsCompleted,
		&i.LoggedAt,
	)
	return i, err
}
