// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO membership (org_id, user_id, role, status, joined_at)
VALUES ($1, $2, $3, 'active', now())
ON CONFLICT (org_id, user_id, role)
DO UPDATE SET status = 'active', joined_at = now()
RETURNING id, org_id, user_id, role, status, invited_by, joined_at, created_at, updated_at
`

type CreateMembershipParams struct {
	OrgID  uuid.UUID  `json:"org_id"`
	UserID uuid.UUID  `json:"user_id"`
	Role   MemberRole `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.OrgID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organization (name, slug, join_code, brand_color)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, join_code, logo_url, brand_color, timezone, status, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name       string `json:"name"`
	Slug       string `json:"slug"`
	JoinCode   string `json:"join_code"`
	BrandColor string `json:"brand_color"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Slug,
		arg.JoinCode,
		arg.BrandColor,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.JoinCode,
		&i.LogoUrl,
		&i.BrandColor,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_token (user_id, token_hash, device_label, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, device_label, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	TokenHash   string      `json:"token_hash"`
	DeviceLabel pgtype.Text `json:"device_label"`
	ExpiresAt   time.Time   `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceLabel,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceLabel,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO app_user (email, password_hash, full_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, full_name, avatar_url, locale, timezone, email_verified_at, is_platform_admin, last_login_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	FullName     string      `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.FullName)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.IsPlatformAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveMembershipByUser = `-- name: GetActiveMembershipByUser :one
SELECT id, org_id, user_id, role, status, invited_by, joined_at, created_at, updated_at FROM membership
WHERE user_id = $1 AND status = 'active'
ORDER BY joined_at DESC
LIMIT 1
`

func (q *Queries) GetActiveMembershipByUser(ctx context.Context, userID uuid.UUID) (Membership, error) {
	row := q.db.QueryRow(ctx, getActiveMembershipByUser, userID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedBy,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, join_code, logo_url, brand_color, timezone, status, created_at, updated_at FROM organization WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.JoinCode,
		&i.LogoUrl,
		&i.BrandColor,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByJoinCode = `-- name: GetOrganizationByJoinCode :one
SELECT id, name, slug, join_code, logo_url, brand_color, timezone, status, created_at, updated_at FROM organization WHERE join_code = $1 AND status = 'active'
`

func (q *Queries) GetOrganizationByJoinCode(ctx context.Context, joinCode string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByJoinCode, joinCode)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.JoinCode,
		&i.LogoUrl,
		&i.BrandColor,
		&i.Timezone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, device_label, expires_at, revoked_at, created_at FROM refresh_token WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceLabel,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, avatar_url, locale, timezone, email_verified_at, is_platform_admin, last_login_at, created_at, updated_at, deleted_at FROM app_user WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.IsPlatformAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, avatar_url, locale, timezone, email_verified_at, is_platform_admin, last_login_at, created_at, updated_at, deleted_at FROM app_user WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.Locale,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.IsPlatformAdmin,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_token SET revoked_at = now() WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, tokenHash)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE app_user SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchUserLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}
