// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AssignedWorkoutStatus string

const (
	AssignedWorkoutStatusPending   AssignedWorkoutStatus = "pending"
	AssignedWorkoutStatusCompleted AssignedWorkoutStatus = "completed"
	AssignedWorkoutStatusSkipped   AssignedWorkoutStatus = "skipped"
)

func (e *AssignedWorkoutStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssignedWorkoutStatus(s)
	case string:
		*e = AssignedWorkoutStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssignedWorkoutStatus: %T", src)
	}
	return nil
}

type NullAssignedWorkoutStatus struct {
	AssignedWorkoutStatus AssignedWorkoutStatus `json:"assigned_workout_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if AssignedWorkoutStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssignedWorkoutStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssignedWorkoutStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssignedWorkoutStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssignedWorkoutStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssignedWorkoutStatus), nil
}

type AssignmentStatus string

const (
	AssignmentStatusActive    AssignmentStatus = "active"
	AssignmentStatusPaused    AssignmentStatus = "paused"
	AssignmentStatusCompleted AssignmentStatus = "completed"
	AssignmentStatusCancelled AssignmentStatus = "cancelled"
)

func (e *AssignmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssignmentStatus(s)
	case string:
		*e = AssignmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssignmentStatus: %T", src)
	}
	return nil
}

type NullAssignmentStatus struct {
	AssignmentStatus AssignmentStatus `json:"assignment_status"`
	Valid            bool             `json:"valid"` // Valid is true if AssignmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssignmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssignmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssignmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssignmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssignmentStatus), nil
}

type AuthProvider string

const (
	AuthProviderPassword AuthProvider = "password"
	AuthProviderGoogle   AuthProvider = "google"
	AuthProviderApple    AuthProvider = "apple"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider `json:"auth_provider"`
	Valid        bool         `json:"valid"` // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type BiologicalSex string

const (
	BiologicalSexMale        BiologicalSex = "male"
	BiologicalSexFemale      BiologicalSex = "female"
	BiologicalSexUnspecified BiologicalSex = "unspecified"
)

func (e *BiologicalSex) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BiologicalSex(s)
	case string:
		*e = BiologicalSex(s)
	default:
		return fmt.Errorf("unsupported scan type for BiologicalSex: %T", src)
	}
	return nil
}

type NullBiologicalSex struct {
	BiologicalSex BiologicalSex `json:"biological_sex"`
	Valid         bool          `json:"valid"` // Valid is true if BiologicalSex is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBiologicalSex) Scan(value interface{}) error {
	if value == nil {
		ns.BiologicalSex, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BiologicalSex.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBiologicalSex) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BiologicalSex), nil
}

type ExerciseMechanic string

const (
	ExerciseMechanicCompound  ExerciseMechanic = "compound"
	ExerciseMechanicIsolation ExerciseMechanic = "isolation"
)

func (e *ExerciseMechanic) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExerciseMechanic(s)
	case string:
		*e = ExerciseMechanic(s)
	default:
		return fmt.Errorf("unsupported scan type for ExerciseMechanic: %T", src)
	}
	return nil
}

type NullExerciseMechanic struct {
	ExerciseMechanic ExerciseMechanic `json:"exercise_mechanic"`
	Valid            bool             `json:"valid"` // Valid is true if ExerciseMechanic is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExerciseMechanic) Scan(value interface{}) error {
	if value == nil {
		ns.ExerciseMechanic, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExerciseMechanic.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExerciseMechanic) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExerciseMechanic), nil
}

type ExperienceLevel string

const (
	ExperienceLevelBeginner     ExperienceLevel = "beginner"
	ExperienceLevelIntermediate ExperienceLevel = "intermediate"
	ExperienceLevelAdvanced     ExperienceLevel = "advanced"
)

func (e *ExperienceLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExperienceLevel(s)
	case string:
		*e = ExperienceLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for ExperienceLevel: %T", src)
	}
	return nil
}

type NullExperienceLevel struct {
	ExperienceLevel ExperienceLevel `json:"experience_level"`
	Valid           bool            `json:"valid"` // Valid is true if ExperienceLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExperienceLevel) Scan(value interface{}) error {
	if value == nil {
		ns.ExperienceLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExperienceLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExperienceLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExperienceLevel), nil
}

type HabitFrequency string

const (
	HabitFrequencyDaily        HabitFrequency = "daily"
	HabitFrequencyWeekly       HabitFrequency = "weekly"
	HabitFrequencySpecificDays HabitFrequency = "specific_days"
)

func (e *HabitFrequency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HabitFrequency(s)
	case string:
		*e = HabitFrequency(s)
	default:
		return fmt.Errorf("unsupported scan type for HabitFrequency: %T", src)
	}
	return nil
}

type NullHabitFrequency struct {
	HabitFrequency HabitFrequency `json:"habit_frequency"`
	Valid          bool           `json:"valid"` // Valid is true if HabitFrequency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHabitFrequency) Scan(value interface{}) error {
	if value == nil {
		ns.HabitFrequency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HabitFrequency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHabitFrequency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HabitFrequency), nil
}

type HabitUnit string

const (
	HabitUnitBoolean     HabitUnit = "boolean"
	HabitUnitCount       HabitUnit = "count"
	HabitUnitMinutes     HabitUnit = "minutes"
	HabitUnitMilliliters HabitUnit = "milliliters"
	HabitUnitSteps       HabitUnit = "steps"
)

func (e *HabitUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HabitUnit(s)
	case string:
		*e = HabitUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for HabitUnit: %T", src)
	}
	return nil
}

type NullHabitUnit struct {
	HabitUnit HabitUnit `json:"habit_unit"`
	Valid     bool      `json:"valid"` // Valid is true if HabitUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHabitUnit) Scan(value interface{}) error {
	if value == nil {
		ns.HabitUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HabitUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHabitUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HabitUnit), nil
}

type MemberRole string

const (
	MemberRoleOwner  MemberRole = "owner"
	MemberRoleAdmin  MemberRole = "admin"
	MemberRoleCoach  MemberRole = "coach"
	MemberRoleClient MemberRole = "client"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type MemberStatus string

const (
	MemberStatusPending MemberStatus = "pending"
	MemberStatusActive  MemberStatus = "active"
	MemberStatusRevoked MemberStatus = "revoked"
)

func (e *MemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberStatus(s)
	case string:
		*e = MemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberStatus: %T", src)
	}
	return nil
}

type NullMemberStatus struct {
	MemberStatus MemberStatus `json:"member_status"`
	Valid        bool         `json:"valid"` // Valid is true if MemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberStatus), nil
}

type MovementPattern string

const (
	MovementPatternSquat          MovementPattern = "squat"
	MovementPatternHinge          MovementPattern = "hinge"
	MovementPatternHorizontalPush MovementPattern = "horizontal_push"
	MovementPatternVerticalPush   MovementPattern = "vertical_push"
	MovementPatternHorizontalPull MovementPattern = "horizontal_pull"
	MovementPatternVerticalPull   MovementPattern = "vertical_pull"
	MovementPatternLunge          MovementPattern = "lunge"
	MovementPatternCarry          MovementPattern = "carry"
	MovementPatternRotation       MovementPattern = "rotation"
	MovementPatternIsolation      MovementPattern = "isolation"
	MovementPatternCardio         MovementPattern = "cardio"
)

func (e *MovementPattern) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MovementPattern(s)
	case string:
		*e = MovementPattern(s)
	default:
		return fmt.Errorf("unsupported scan type for MovementPattern: %T", src)
	}
	return nil
}

type NullMovementPattern struct {
	MovementPattern MovementPattern `json:"movement_pattern"`
	Valid           bool            `json:"valid"` // Valid is true if MovementPattern is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMovementPattern) Scan(value interface{}) error {
	if value == nil {
		ns.MovementPattern, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MovementPattern.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMovementPattern) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MovementPattern), nil
}

type OrgStatus string

const (
	OrgStatusActive    OrgStatus = "active"
	OrgStatusSuspended OrgStatus = "suspended"
	OrgStatusCancelled OrgStatus = "cancelled"
)

func (e *OrgStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrgStatus(s)
	case string:
		*e = OrgStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrgStatus: %T", src)
	}
	return nil
}

type NullOrgStatus struct {
	OrgStatus OrgStatus `json:"org_status"`
	Valid     bool      `json:"valid"` // Valid is true if OrgStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrgStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrgStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrgStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrgStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrgStatus), nil
}

type ProgramStatus string

const (
	ProgramStatusDraft     ProgramStatus = "draft"
	ProgramStatusPublished ProgramStatus = "published"
	ProgramStatusArchived  ProgramStatus = "archived"
)

func (e *ProgramStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProgramStatus(s)
	case string:
		*e = ProgramStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProgramStatus: %T", src)
	}
	return nil
}

type NullProgramStatus struct {
	ProgramStatus ProgramStatus `json:"program_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProgramStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProgramStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProgramStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProgramStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProgramStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProgramStatus), nil
}

type ProgressionType string

const (
	ProgressionTypeDoubleProgression ProgressionType = "double_progression"
	ProgressionTypeLinearLoad        ProgressionType = "linear_load"
	ProgressionTypeRpeAutoregulated  ProgressionType = "rpe_autoregulated"
	ProgressionTypePercentage1rm     ProgressionType = "percentage_1rm"
	ProgressionTypeNone              ProgressionType = "none"
)

func (e *ProgressionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProgressionType(s)
	case string:
		*e = ProgressionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProgressionType: %T", src)
	}
	return nil
}

type NullProgressionType struct {
	ProgressionType ProgressionType `json:"progression_type"`
	Valid           bool            `json:"valid"` // Valid is true if ProgressionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProgressionType) Scan(value interface{}) error {
	if value == nil {
		ns.ProgressionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProgressionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProgressionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProgressionType), nil
}

type RecordType string

const (
	RecordTypeMaxWeight    RecordType = "max_weight"
	RecordTypeMaxReps      RecordType = "max_reps"
	RecordTypeEstimated1rm RecordType = "estimated_1rm"
	RecordTypeMaxVolumeSet RecordType = "max_volume_set"
)

func (e *RecordType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordType(s)
	case string:
		*e = RecordType(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordType: %T", src)
	}
	return nil
}

type NullRecordType struct {
	RecordType RecordType `json:"record_type"`
	Valid      bool       `json:"valid"` // Valid is true if RecordType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordType) Scan(value interface{}) error {
	if value == nil {
		ns.RecordType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordType), nil
}

type SessionStatus string

const (
	SessionStatusInProgress SessionStatus = "in_progress"
	SessionStatusCompleted  SessionStatus = "completed"
	SessionStatusAbandoned  SessionStatus = "abandoned"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus `json:"session_status"`
	Valid         bool          `json:"valid"` // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type SetType string

const (
	SetTypeWarmup  SetType = "warmup"
	SetTypeWorking SetType = "working"
	SetTypeDrop    SetType = "drop"
	SetTypeFailure SetType = "failure"
	SetTypeBackoff SetType = "backoff"
)

func (e *SetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SetType(s)
	case string:
		*e = SetType(s)
	default:
		return fmt.Errorf("unsupported scan type for SetType: %T", src)
	}
	return nil
}

type NullSetType struct {
	SetType SetType `json:"set_type"`
	Valid   bool    `json:"valid"` // Valid is true if SetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSetType) Scan(value interface{}) error {
	if value == nil {
		ns.SetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SetType), nil
}

type StreakKind string

const (
	StreakKindWorkout StreakKind = "workout"
	StreakKindHabit   StreakKind = "habit"
	StreakKindOverall StreakKind = "overall"
)

func (e *StreakKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StreakKind(s)
	case string:
		*e = StreakKind(s)
	default:
		return fmt.Errorf("unsupported scan type for StreakKind: %T", src)
	}
	return nil
}

type NullStreakKind struct {
	StreakKind StreakKind `json:"streak_kind"`
	Valid      bool       `json:"valid"` // Valid is true if StreakKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStreakKind) Scan(value interface{}) error {
	if value == nil {
		ns.StreakKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StreakKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStreakKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StreakKind), nil
}

type SuggestionKind string

const (
	SuggestionKindVolumeAdjust SuggestionKind = "volume_adjust"
	SuggestionKindLoadAdjust   SuggestionKind = "load_adjust"
	SuggestionKindExerciseSwap SuggestionKind = "exercise_swap"
	SuggestionKindDeload       SuggestionKind = "deload"
	SuggestionKindRestDay      SuggestionKind = "rest_day"
	SuggestionKindHabitNudge   SuggestionKind = "habit_nudge"
)

func (e *SuggestionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SuggestionKind(s)
	case string:
		*e = SuggestionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for SuggestionKind: %T", src)
	}
	return nil
}

type NullSuggestionKind struct {
	SuggestionKind SuggestionKind `json:"suggestion_kind"`
	Valid          bool           `json:"valid"` // Valid is true if SuggestionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSuggestionKind) Scan(value interface{}) error {
	if value == nil {
		ns.SuggestionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SuggestionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSuggestionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SuggestionKind), nil
}

type SuggestionStatus string

const (
	SuggestionStatusPending     SuggestionStatus = "pending"
	SuggestionStatusApproved    SuggestionStatus = "approved"
	SuggestionStatusRejected    SuggestionStatus = "rejected"
	SuggestionStatusExpired     SuggestionStatus = "expired"
	SuggestionStatusAutoApplied SuggestionStatus = "auto_applied"
)

func (e *SuggestionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SuggestionStatus(s)
	case string:
		*e = SuggestionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SuggestionStatus: %T", src)
	}
	return nil
}

type NullSuggestionStatus struct {
	SuggestionStatus SuggestionStatus `json:"suggestion_status"`
	Valid            bool             `json:"valid"` // Valid is true if SuggestionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSuggestionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SuggestionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SuggestionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSuggestionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SuggestionStatus), nil
}

type TrackingMode string

const (
	TrackingModeWeightReps         TrackingMode = "weight_reps"
	TrackingModeBodyweightReps     TrackingMode = "bodyweight_reps"
	TrackingModeWeightedBodyweight TrackingMode = "weighted_bodyweight"
	TrackingModeDuration           TrackingMode = "duration"
	TrackingModeDistanceDuration   TrackingMode = "distance_duration"
)

func (e *TrackingMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrackingMode(s)
	case string:
		*e = TrackingMode(s)
	default:
		return fmt.Errorf("unsupported scan type for TrackingMode: %T", src)
	}
	return nil
}

type NullTrackingMode struct {
	TrackingMode TrackingMode `json:"tracking_mode"`
	Valid        bool         `json:"valid"` // Valid is true if TrackingMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrackingMode) Scan(value interface{}) error {
	if value == nil {
		ns.TrackingMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrackingMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrackingMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrackingMode), nil
}

type TrainingGoal string

const (
	TrainingGoalStrength      TrainingGoal = "strength"
	TrainingGoalHypertrophy   TrainingGoal = "hypertrophy"
	TrainingGoalFatLoss       TrainingGoal = "fat_loss"
	TrainingGoalEndurance     TrainingGoal = "endurance"
	TrainingGoalGeneralHealth TrainingGoal = "general_health"
)

func (e *TrainingGoal) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrainingGoal(s)
	case string:
		*e = TrainingGoal(s)
	default:
		return fmt.Errorf("unsupported scan type for TrainingGoal: %T", src)
	}
	return nil
}

type NullTrainingGoal struct {
	TrainingGoal TrainingGoal `json:"training_goal"`
	Valid        bool         `json:"valid"` // Valid is true if TrainingGoal is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrainingGoal) Scan(value interface{}) error {
	if value == nil {
		ns.TrainingGoal, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrainingGoal.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrainingGoal) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrainingGoal), nil
}

type XpSource string

const (
	XpSourceSession        XpSource = "session"
	XpSourceHabit          XpSource = "habit"
	XpSourcePersonalRecord XpSource = "personal_record"
	XpSourceStreak         XpSource = "streak"
	XpSourceAchievement    XpSource = "achievement"
)

func (e *XpSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = XpSource(s)
	case string:
		*e = XpSource(s)
	default:
		return fmt.Errorf("unsupported scan type for XpSource: %T", src)
	}
	return nil
}

type NullXpSource struct {
	XpSource XpSource `json:"xp_source"`
	Valid    bool     `json:"valid"` // Valid is true if XpSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullXpSource) Scan(value interface{}) error {
	if value == nil {
		ns.XpSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.XpSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullXpSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.XpSource), nil
}

type Achievement struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Icon        string    `json:"icon"`
	Tier        int16     `json:"tier"`
	XpReward    int32     `json:"xp_reward"`
	Criteria    []byte    `json:"criteria"`
}

type AiSuggestion struct {
	ID            uuid.UUID        `json:"id"`
	OrgID         uuid.UUID        `json:"org_id"`
	ClientUserID  uuid.UUID        `json:"client_user_id"`
	CoachUserID   pgtype.UUID      `json:"coach_user_id"`
	AssignmentID  pgtype.UUID      `json:"assignment_id"`
	Kind          SuggestionKind   `json:"kind"`
	Payload       []byte           `json:"payload"`
	Rationale     string           `json:"rationale"`
	Confidence    *float64         `json:"confidence"`
	Model         string           `json:"model"`
	InputSnapshot []byte           `json:"input_snapshot"`
	Status        SuggestionStatus `json:"status"`
	ReviewedBy    pgtype.UUID      `json:"reviewed_by"`
	ReviewedAt    *time.Time       `json:"reviewed_at"`
	AppliedAt     *time.Time       `json:"applied_at"`
	ExpiresAt     time.Time        `json:"expires_at"`
	CreatedAt     time.Time        `json:"created_at"`
}

type AppUser struct {
	ID              uuid.UUID   `json:"id"`
	Email           string      `json:"email"`
	PasswordHash    pgtype.Text `json:"password_hash"`
	FullName        string      `json:"full_name"`
	AvatarUrl       pgtype.Text `json:"avatar_url"`
	Locale          string      `json:"locale"`
	Timezone        string      `json:"timezone"`
	EmailVerifiedAt *time.Time  `json:"email_verified_at"`
	IsPlatformAdmin bool        `json:"is_platform_admin"`
	LastLoginAt     *time.Time  `json:"last_login_at"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	DeletedAt       *time.Time  `json:"deleted_at"`
}

type AssignedExercise struct {
	ID                uuid.UUID   `json:"id"`
	AssignedWorkoutID uuid.UUID   `json:"assigned_workout_id"`
	ExerciseID        uuid.UUID   `json:"exercise_id"`
	OrderIndex        int16       `json:"order_index"`
	SupersetGroup     pgtype.Int2 `json:"superset_group"`
	TargetSets        int16       `json:"target_sets"`
	TargetRepsMin     pgtype.Int2 `json:"target_reps_min"`
	TargetRepsMax     pgtype.Int2 `json:"target_reps_max"`
	TargetRpe         *float64    `json:"target_rpe"`
	TargetWeightKg    *float64    `json:"target_weight_kg"`
	RestSeconds       int16       `json:"rest_seconds"`
	Tempo             pgtype.Text `json:"tempo"`
	Note              pgtype.Text `json:"note"`
	ProgressionRuleID pgtype.UUID `json:"progression_rule_id"`
	OverrideSource    pgtype.Text `json:"override_source"`
}

type AssignedWorkout struct {
	ID              uuid.UUID             `json:"id"`
	AssignmentID    uuid.UUID             `json:"assignment_id"`
	SourceWorkoutID pgtype.UUID           `json:"source_workout_id"`
	WeekNumber      int16                 `json:"week_number"`
	DayIndex        int16                 `json:"day_index"`
	Name            string                `json:"name"`
	Note            pgtype.Text           `json:"note"`
	IsDeload        bool                  `json:"is_deload"`
	ScheduledOn     *time.Time            `json:"scheduled_on"`
	Status          AssignedWorkoutStatus `json:"status"`
}

type Assignment struct {
	ID           uuid.UUID        `json:"id"`
	OrgID        uuid.UUID        `json:"org_id"`
	ProgramID    pgtype.UUID      `json:"program_id"`
	ClientUserID uuid.UUID        `json:"client_user_id"`
	CoachUserID  pgtype.UUID      `json:"coach_user_id"`
	Name         string           `json:"name"`
	StartDate    time.Time        `json:"start_date"`
	EndDate      *time.Time       `json:"end_date"`
	Status       AssignmentStatus `json:"status"`
	CreatedAt    time.Time        `json:"created_at"`
	UpdatedAt    time.Time        `json:"updated_at"`
}

type AuditLog struct {
	ID          int64       `json:"id"`
	OrgID       pgtype.UUID `json:"org_id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    string      `json:"entity_id"`
	Metadata    []byte      `json:"metadata"`
	IpAddress   *netip.Addr `json:"ip_address"`
	CreatedAt   time.Time   `json:"created_at"`
}

type BodyMetric struct {
	ID           int64       `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	MeasuredOn   time.Time   `json:"measured_on"`
	WeightKg     *float64    `json:"weight_kg"`
	BodyFatPct   *float64    `json:"body_fat_pct"`
	Measurements []byte      `json:"measurements"`
	Note         pgtype.Text `json:"note"`
	CreatedAt    time.Time   `json:"created_at"`
}

type ClientHabit struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	HabitID      uuid.UUID      `json:"habit_id"`
	AssignedBy   pgtype.UUID    `json:"assigned_by"`
	TargetValue  *float64       `json:"target_value"`
	Frequency    HabitFrequency `json:"frequency"`
	DaysOfWeek   []int16        `json:"days_of_week"`
	ReminderTime pgtype.Time    `json:"reminder_time"`
	StartedOn    time.Time      `json:"started_on"`
	EndedOn      *time.Time     `json:"ended_on"`
}

type ClientProfile struct {
	UserID             uuid.UUID       `json:"user_id"`
	BirthDate          *time.Time      `json:"birth_date"`
	Sex                BiologicalSex   `json:"sex"`
	HeightCm           *float64        `json:"height_cm"`
	Experience         ExperienceLevel `json:"experience"`
	PrimaryGoal        TrainingGoal    `json:"primary_goal"`
	DaysPerWeek        int16           `json:"days_per_week"`
	SessionMinutes     int16           `json:"session_minutes"`
	AvailableEquipment []string        `json:"available_equipment"`
	Limitations        pgtype.Text     `json:"limitations"`
	UnitSystem         string          `json:"unit_system"`
	OnboardedAt        *time.Time      `json:"onboarded_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type CoachClient struct {
	ID           uuid.UUID  `json:"id"`
	OrgID        uuid.UUID  `json:"org_id"`
	CoachUserID  uuid.UUID  `json:"coach_user_id"`
	ClientUserID uuid.UUID  `json:"client_user_id"`
	StartedAt    time.Time  `json:"started_at"`
	EndedAt      *time.Time `json:"ended_at"`
}

type DeviceToken struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Token      string    `json:"token"`
	Platform   string    `json:"platform"`
	LastSeenAt time.Time `json:"last_seen_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type Exercise struct {
	ID               uuid.UUID        `json:"id"`
	OrgID            pgtype.UUID      `json:"org_id"`
	Slug             string           `json:"slug"`
	Name             string           `json:"name"`
	Description      pgtype.Text      `json:"description"`
	Instructions     []string         `json:"instructions"`
	Pattern          MovementPattern  `json:"pattern"`
	Mechanic         ExerciseMechanic `json:"mechanic"`
	PrimaryMuscle    string           `json:"primary_muscle"`
	SecondaryMuscles []string         `json:"secondary_muscles"`
	Equipment        []string         `json:"equipment"`
	Difficulty       ExperienceLevel  `json:"difficulty"`
	Tracking         TrackingMode     `json:"tracking"`
	IsUnilateral     bool             `json:"is_unilateral"`
	VideoUrl         pgtype.Text      `json:"video_url"`
	ThumbnailUrl     pgtype.Text      `json:"thumbnail_url"`
	CreatedBy        pgtype.UUID      `json:"created_by"`
	IsActive         bool             `json:"is_active"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
}

type ExerciseAlternative struct {
	ExerciseID    uuid.UUID   `json:"exercise_id"`
	AlternativeID uuid.UUID   `json:"alternative_id"`
	Reason        pgtype.Text `json:"reason"`
}

type Habit struct {
	ID            uuid.UUID   `json:"id"`
	OrgID         pgtype.UUID `json:"org_id"`
	Slug          string      `json:"slug"`
	Name          string      `json:"name"`
	Icon          string      `json:"icon"`
	Unit          HabitUnit   `json:"unit"`
	DefaultTarget *float64    `json:"default_target"`
	IsSystem      bool        `json:"is_system"`
	CreatedAt     time.Time   `json:"created_at"`
}

type HabitLog struct {
	ID            int64     `json:"id"`
	ClientLocalID uuid.UUID `json:"client_local_id"`
	ClientHabitID uuid.UUID `json:"client_habit_id"`
	UserID        uuid.UUID `json:"user_id"`
	LogDate       time.Time `json:"log_date"`
	Value         float64   `json:"value"`
	IsCompleted   bool      `json:"is_completed"`
	LoggedAt      time.Time `json:"logged_at"`
}

type Membership struct {
	ID        uuid.UUID    `json:"id"`
	OrgID     uuid.UUID    `json:"org_id"`
	UserID    uuid.UUID    `json:"user_id"`
	Role      MemberRole   `json:"role"`
	Status    MemberStatus `json:"status"`
	InvitedBy pgtype.UUID  `json:"invited_by"`
	JoinedAt  *time.Time   `json:"joined_at"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Organization struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	Slug       string      `json:"slug"`
	JoinCode   string      `json:"join_code"`
	LogoUrl    pgtype.Text `json:"logo_url"`
	BrandColor string      `json:"brand_color"`
	Timezone   string      `json:"timezone"`
	Status     OrgStatus   `json:"status"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type PersonalRecord struct {
	ID         int64       `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	ExerciseID uuid.UUID   `json:"exercise_id"`
	Type       RecordType  `json:"type"`
	Value      float64     `json:"value"`
	SetLogID   pgtype.Int8 `json:"set_log_id"`
	AchievedAt time.Time   `json:"achieved_at"`
}

type Program struct {
	ID          uuid.UUID       `json:"id"`
	OrgID       uuid.UUID       `json:"org_id"`
	CreatedBy   uuid.UUID       `json:"created_by"`
	Name        string          `json:"name"`
	Description pgtype.Text     `json:"description"`
	Goal        TrainingGoal    `json:"goal"`
	Level       ExperienceLevel `json:"level"`
	TotalWeeks  int16           `json:"total_weeks"`
	DaysPerWeek int16           `json:"days_per_week"`
	Status      ProgramStatus   `json:"status"`
	IsShared    bool            `json:"is_shared"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type ProgramExercise struct {
	ID                uuid.UUID   `json:"id"`
	ProgramWorkoutID  uuid.UUID   `json:"program_workout_id"`
	ExerciseID        uuid.UUID   `json:"exercise_id"`
	OrderIndex        int16       `json:"order_index"`
	SupersetGroup     pgtype.Int2 `json:"superset_group"`
	TargetSets        int16       `json:"target_sets"`
	TargetRepsMin     pgtype.Int2 `json:"target_reps_min"`
	TargetRepsMax     pgtype.Int2 `json:"target_reps_max"`
	TargetRpe         *float64    `json:"target_rpe"`
	TargetPct1rm      *float64    `json:"target_pct_1rm"`
	RestSeconds       int16       `json:"rest_seconds"`
	Tempo             pgtype.Text `json:"tempo"`
	Note              pgtype.Text `json:"note"`
	ProgressionRuleID pgtype.UUID `json:"progression_rule_id"`
}

type ProgramWorkout struct {
	ID               uuid.UUID   `json:"id"`
	ProgramID        uuid.UUID   `json:"program_id"`
	WeekNumber       int16       `json:"week_number"`
	DayIndex         int16       `json:"day_index"`
	Name             string      `json:"name"`
	Note             pgtype.Text `json:"note"`
	IsDeload         bool        `json:"is_deload"`
	EstimatedMinutes pgtype.Int2 `json:"estimated_minutes"`
}

type ProgressPhoto struct {
	ID              uuid.UUID   `json:"id"`
	UserID          uuid.UUID   `json:"user_id"`
	StorageKey      string      `json:"storage_key"`
	Pose            pgtype.Text `json:"pose"`
	TakenOn         time.Time   `json:"taken_on"`
	SharedWithCoach bool        `json:"shared_with_coach"`
	CreatedAt       time.Time   `json:"created_at"`
}

type ProgressionRule struct {
	ID        uuid.UUID       `json:"id"`
	OrgID     pgtype.UUID     `json:"org_id"`
	Name      string          `json:"name"`
	Type      ProgressionType `json:"type"`
	Params    []byte          `json:"params"`
	IsSystem  bool            `json:"is_system"`
	CreatedAt time.Time       `json:"created_at"`
}

type RefreshToken struct {
	ID          uuid.UUID   `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
	TokenHash   string      `json:"token_hash"`
	DeviceLabel pgtype.Text `json:"device_label"`
	ExpiresAt   time.Time   `json:"expires_at"`
	RevokedAt   *time.Time  `json:"revoked_at"`
	CreatedAt   time.Time   `json:"created_at"`
}

type SessionExercise struct {
	ID                 uuid.UUID   `json:"id"`
	SessionID          uuid.UUID   `json:"session_id"`
	ExerciseID         uuid.UUID   `json:"exercise_id"`
	AssignedExerciseID pgtype.UUID `json:"assigned_exercise_id"`
	OrderIndex         int16       `json:"order_index"`
	SupersetGroup      pgtype.Int2 `json:"superset_group"`
	Note               pgtype.Text `json:"note"`
}

type SetLog struct {
	ID                int64       `json:"id"`
	ClientLocalID     uuid.UUID   `json:"client_local_id"`
	SessionExerciseID uuid.UUID   `json:"session_exercise_id"`
	UserID            uuid.UUID   `json:"user_id"`
	ExerciseID        uuid.UUID   `json:"exercise_id"`
	SetNumber         int16       `json:"set_number"`
	Type              SetType     `json:"type"`
	WeightKg          *float64    `json:"weight_kg"`
	Reps              pgtype.Int2 `json:"reps"`
	Rpe               *float64    `json:"rpe"`
	Rir               pgtype.Int2 `json:"rir"`
	DurationSeconds   pgtype.Int4 `json:"duration_seconds"`
	DistanceM         *float64    `json:"distance_m"`
	RestTakenSeconds  pgtype.Int4 `json:"rest_taken_seconds"`
	IsCompleted       bool        `json:"is_completed"`
	PerformedAt       time.Time   `json:"performed_at"`
}

type UserAchievement struct {
	UserID        uuid.UUID  `json:"user_id"`
	AchievementID uuid.UUID  `json:"achievement_id"`
	Progress      float64    `json:"progress"`
	EarnedAt      *time.Time `json:"earned_at"`
}

type UserIdentity struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	Provider    AuthProvider `json:"provider"`
	ProviderUid string       `json:"provider_uid"`
	CreatedAt   time.Time    `json:"created_at"`
}

type UserStat struct {
	UserID        uuid.UUID `json:"user_id"`
	TotalXp       int32     `json:"total_xp"`
	Level         int16     `json:"level"`
	TotalSessions int32     `json:"total_sessions"`
	TotalVolumeKg float64   `json:"total_volume_kg"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type UserStreak struct {
	UserID       uuid.UUID  `json:"user_id"`
	Kind         StreakKind `json:"kind"`
	CurrentCount int32      `json:"current_count"`
	LongestCount int32      `json:"longest_count"`
	LastActiveOn *time.Time `json:"last_active_on"`
	FreezesLeft  int16      `json:"freezes_left"`
}

type WorkoutSession struct {
	ID                uuid.UUID     `json:"id"`
	ClientLocalID     uuid.UUID     `json:"client_local_id"`
	UserID            uuid.UUID     `json:"user_id"`
	OrgID             pgtype.UUID   `json:"org_id"`
	AssignedWorkoutID pgtype.UUID   `json:"assigned_workout_id"`
	Name              string        `json:"name"`
	Status            SessionStatus `json:"status"`
	StartedAt         time.Time     `json:"started_at"`
	EndedAt           *time.Time    `json:"ended_at"`
	DurationSeconds   pgtype.Int4   `json:"duration_seconds"`
	TotalVolumeKg     float64       `json:"total_volume_kg"`
	PerceivedEffort   pgtype.Int2   `json:"perceived_effort"`
	Mood              pgtype.Int2   `json:"mood"`
	Notes             pgtype.Text   `json:"notes"`
	SyncedAt          time.Time     `json:"synced_at"`
	CreatedAt         time.Time     `json:"created_at"`
}

type XpEvent struct {
	ID          int64       `json:"id"`
	UserID      uuid.UUID   `json:"user_id"`
	Source      XpSource    `json:"source"`
	Points      int32       `json:"points"`
	ReferenceID pgtype.Text `json:"reference_id"`
	CreatedAt   time.Time   `json:"created_at"`
}
