// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getClientProfile = `-- name: GetClientProfile :one
SELECT user_id, birth_date, sex, height_cm, experience, primary_goal, days_per_week, session_minutes, available_equipment, limitations, unit_system, onboarded_at, updated_at FROM client_profile WHERE user_id = $1
`

func (q *Queries) GetClientProfile(ctx context.Context, userID uuid.UUID) (ClientProfile, error) {
	row := q.db.QueryRow(ctx, getClientProfile, userID)
	var i ClientProfile
	err := row.Scan(
		&i.UserID,
		&i.BirthDate,
		&i.Sex,
		&i.HeightCm,
		&i.Experience,
		&i.PrimaryGoal,
		&i.DaysPerWeek,
		&i.SessionMinutes,
		&i.AvailableEquipment,
		&i.Limitations,
		&i.UnitSystem,
		&i.OnboardedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertClientProfile = `-- name: UpsertClientProfile :one
INSERT INTO client_profile (
  user_id, birth_date, sex, height_cm, experience, primary_goal,
  days_per_week, session_minutes, available_equipment, limitations,
  unit_system, onboarded_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now()
)
ON CONFLICT (user_id) DO UPDATE SET
  birth_date = EXCLUDED.birth_date,
  sex = EXCLUDED.sex,
  height_cm = EXCLUDED.height_cm,
  experience = EXCLUDED.experience,
  primary_goal = EXCLUDED.primary_goal,
  days_per_week = EXCLUDED.days_per_week,
  session_minutes = EXCLUDED.session_minutes,
  available_equipment = EXCLUDED.available_equipment,
  limitations = EXCLUDED.limitations,
  unit_system = EXCLUDED.unit_system,
  -- onboarded_at marca la primera vez: no se pisa en ediciones posteriores.
  onboarded_at = COALESCE(client_profile.onboarded_at, now())
RETURNING user_id, birth_date, sex, height_cm, experience, primary_goal, days_per_week, session_minutes, available_equipment, limitations, unit_system, onboarded_at, updated_at
`

type UpsertClientProfileParams struct {
	UserID             uuid.UUID       `json:"user_id"`
	BirthDate          *time.Time      `json:"birth_date"`
	Sex                BiologicalSex   `json:"sex"`
	HeightCm           *float64        `json:"height_cm"`
	Experience         ExperienceLevel `json:"experience"`
	PrimaryGoal        TrainingGoal    `json:"primary_goal"`
	DaysPerWeek        int16           `json:"days_per_week"`
	SessionMinutes     int16           `json:"session_minutes"`
	AvailableEquipment []string        `json:"available_equipment"`
	Limitations        pgtype.Text     `json:"limitations"`
	UnitSystem         string          `json:"unit_system"`
}

func (q *Queries) UpsertClientProfile(ctx context.Context, arg UpsertClientProfileParams) (ClientProfile, error) {
	row := q.db.QueryRow(ctx, upsertClientProfile,
		arg.UserID,
		arg.BirthDate,
		arg.Sex,
		arg.HeightCm,
		arg.Experience,
		arg.PrimaryGoal,
		arg.DaysPerWeek,
		arg.SessionMinutes,
		arg.AvailableEquipment,
		arg.Limitations,
		arg.UnitSystem,
	)
	var i ClientProfile
	err := row.Scan(
		&i.UserID,
		&i.BirthDate,
		&i.Sex,
		&i.HeightCm,
		&i.Experience,
		&i.PrimaryGoal,
		&i.DaysPerWeek,
		&i.SessionMinutes,
		&i.AvailableEquipment,
		&i.Limitations,
		&i.UnitSystem,
		&i.OnboardedAt,
		&i.UpdatedAt,
	)
	return i, err
}
