// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listBodyMetrics = `-- name: ListBodyMetrics :many
SELECT id, user_id, measured_on, weight_kg, body_fat_pct, measurements, note, created_at FROM body_metric WHERE user_id = $1 ORDER BY measured_on DESC LIMIT $2
`

type ListBodyMetricsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListBodyMetrics(ctx context.Context, arg ListBodyMetricsParams) ([]BodyMetric, error) {
	rows, err := q.db.Query(ctx, listBodyMetrics, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BodyMetric{}
	for rows.Next() {
		var i BodyMetric
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MeasuredOn,
			&i.WeightKg,
			&i.BodyFatPct,
			&i.Measurements,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalRecords = `-- name: ListPersonalRecords :many
SELECT id, user_id, exercise_id, type, value, set_log_id, achieved_at FROM personal_record
WHERE user_id = $1 AND ($2::uuid IS NULL OR exercise_id = $2)
ORDER BY achieved_at DESC
`

type ListPersonalRecordsParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	ExerciseID pgtype.UUID `json:"exercise_id"`
}

func (q *Queries) ListPersonalRecords(ctx context.Context, arg ListPersonalRecordsParams) ([]PersonalRecord, error) {
	rows, err := q.db.Query(ctx, listPersonalRecords, arg.UserID, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonalRecord{}
	for rows.Next() {
		var i PersonalRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseID,
			&i.Type,
			&i.Value,
			&i.SetLogID,
			&i.AchievedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForVolume = `-- name: ListSessionsForVolume :many
SELECT id, started_at, total_volume_kg, duration_seconds
FROM workout_session
WHERE user_id = $1 AND status = 'completed' AND started_at >= $2
ORDER BY started_at DESC
`

type ListSessionsForVolumeParams struct {
	UserID    uuid.UUID `json:"user_id"`
	StartedAt time.Time `json:"started_at"`
}

type ListSessionsForVolumeRow struct {
	ID              uuid.UUID   `json:"id"`
	StartedAt       time.Time   `json:"started_at"`
	TotalVolumeKg   float64     `json:"total_volume_kg"`
	DurationSeconds pgtype.Int4 `json:"duration_seconds"`
}

func (q *Queries) ListSessionsForVolume(ctx context.Context, arg ListSessionsForVolumeParams) ([]ListSessionsForVolumeRow, error) {
	rows, err := q.db.Query(ctx, listSessionsForVolume, arg.UserID, arg.StartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsForVolumeRow{}
	for rows.Next() {
		var i ListSessionsForVolumeRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.TotalVolumeKg,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetLogsForExercise = `-- name: ListSetLogsForExercise :many
SELECT id, client_local_id, session_exercise_id, user_id, exercise_id, set_number, type, weight_kg, reps, rpe, rir, duration_seconds, distance_m, rest_taken_seconds, is_completed, performed_at FROM set_log
WHERE user_id = $1 AND exercise_id = $2 AND type = 'working' AND is_completed = true
  AND performed_at >= $3
ORDER BY performed_at DESC
LIMIT $4
`

type ListSetLogsForExerciseParams struct {
	UserID      uuid.UUID `json:"user_id"`
	ExerciseID  uuid.UUID `json:"exercise_id"`
	PerformedAt time.Time `json:"performed_at"`
	Limit       int32     `json:"limit"`
}

func (q *Queries) ListSetLogsForExercise(ctx context.Context, arg ListSetLogsForExerciseParams) ([]SetLog, error) {
	rows, err := q.db.Query(ctx, listSetLogsForExercise,
		arg.UserID,
		arg.ExerciseID,
		arg.PerformedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetLog{}
	for rows.Next() {
		var i SetLog
		if err := rows.Scan(
			&i.ID,
			&i.ClientLocalID,
			&i.SessionExerciseID,
			&i.UserID,
			&i.ExerciseID,
			&i.SetNumber,
			&i.Type,
			&i.WeightKg,
			&i.Reps,
			&i.Rpe,
			&i.Rir,
			&i.DurationSeconds,
			&i.DistanceM,
			&i.RestTakenSeconds,
			&i.IsCompleted,
			&i.PerformedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBodyMetric = `-- name: UpsertBodyMetric :one
INSERT INTO body_metric (user_id, measured_on, weight_kg, body_fat_pct, note)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, measured_on) DO UPDATE SET
  weight_kg = EXCLUDED.weight_kg, body_fat_pct = EXCLUDED.body_fat_pct, note = EXCLUDED.note
RETURNING id, user_id, measured_on, weight_kg, body_fat_pct, measurements, note, created_at
`

type UpsertBodyMetricParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	MeasuredOn time.Time   `json:"measured_on"`
	WeightKg   *float64    `json:"weight_kg"`
	BodyFatPct *float64    `json:"body_fat_pct"`
	Note       pgtype.Text `json:"note"`
}

func (q *Queries) UpsertBodyMetric(ctx context.Context, arg UpsertBodyMetricParams) (BodyMetric, error) {
	row := q.db.QueryRow(ctx, upsertBodyMetric,
		arg.UserID,
		arg.MeasuredOn,
		arg.WeightKg,
		arg.BodyFatPct,
		arg.Note,
	)
	var i BodyMetric
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MeasuredOn,
		&i.WeightKg,
		&i.BodyFatPct,
		&i.Measurements,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
