// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: program.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProgram = `-- name: CreateProgram :one
INSERT INTO program (org_id, created_by, name, description, goal, level, total_weeks, days_per_week)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, created_by, name, description, goal, level, total_weeks, days_per_week, status, is_shared, created_at, updated_at
`

type CreateProgramParams struct {
	OrgID       uuid.UUID       `json:"org_id"`
	CreatedBy   uuid.UUID       `json:"created_by"`
	Name        string          `json:"name"`
	Description pgtype.Text     `json:"description"`
	Goal        TrainingGoal    `json:"goal"`
	Level       ExperienceLevel `json:"level"`
	TotalWeeks  int16           `json:"total_weeks"`
	DaysPerWeek int16           `json:"days_per_week"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, createProgram,
		arg.OrgID,
		arg.CreatedBy,
		arg.Name,
		arg.Description,
		arg.Goal,
		arg.Level,
		arg.TotalWeeks,
		arg.DaysPerWeek,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.Goal,
		&i.Level,
		&i.TotalWeeks,
		&i.DaysPerWeek,
		&i.Status,
		&i.IsShared,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProgramExercise = `-- name: CreateProgramExercise :one
INSERT INTO program_exercise (
  program_workout_id, exercise_id, order_index, superset_group, target_sets,
  target_reps_min, target_reps_max, target_rpe, target_pct_1rm, rest_seconds,
  tempo, note, progression_rule_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, program_workout_id, exercise_id, order_index, superset_group, target_sets, target_reps_min, target_reps_max, target_rpe, target_pct_1rm, rest_seconds, tempo, note, progression_rule_id
`

type CreateProgramExerciseParams struct {
	ProgramWorkoutID  uuid.UUID   `json:"program_workout_id"`
	ExerciseID        uuid.UUID   `json:"exercise_id"`
	OrderIndex        int16       `json:"order_index"`
	SupersetGroup     pgtype.Int2 `json:"superset_group"`
	TargetSets        int16       `json:"target_sets"`
	TargetRepsMin     pgtype.Int2 `json:"target_reps_min"`
	TargetRepsMax     pgtype.Int2 `json:"target_reps_max"`
	TargetRpe         *float64    `json:"target_rpe"`
	TargetPct1rm      *float64    `json:"target_pct_1rm"`
	RestSeconds       int16       `json:"rest_seconds"`
	Tempo             pgtype.Text `json:"tempo"`
	Note              pgtype.Text `json:"note"`
	ProgressionRuleID pgtype.UUID `json:"progression_rule_id"`
}

func (q *Queries) CreateProgramExercise(ctx context.Context, arg CreateProgramExerciseParams) (ProgramExercise, error) {
	row := q.db.QueryRow(ctx, createProgramExercise,
		arg.ProgramWorkoutID,
		arg.ExerciseID,
		arg.OrderIndex,
		arg.SupersetGroup,
		arg.TargetSets,
		arg.TargetRepsMin,
		arg.TargetRepsMax,
		arg.TargetRpe,
		arg.TargetPct1rm,
		arg.RestSeconds,
		arg.Tempo,
		arg.Note,
		arg.ProgressionRuleID,
	)
	var i ProgramExercise
	err := row.Scan(
		&i.ID,
		&i.ProgramWorkoutID,
		&i.ExerciseID,
		&i.OrderIndex,
		&i.SupersetGroup,
		&i.TargetSets,
		&i.TargetRepsMin,
		&i.TargetRepsMax,
		&i.TargetRpe,
		&i.TargetPct1rm,
		&i.RestSeconds,
		&i.Tempo,
		&i.Note,
		&i.ProgressionRuleID,
	)
	return i, err
}

const createProgramWorkout = `-- name: CreateProgramWorkout :one
INSERT INTO program_workout (program_id, week_number, day_index, name, note, is_deload, estimated_minutes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, program_id, week_number, day_index, name, note, is_deload, estimated_minutes
`

type CreateProgramWorkoutParams struct {
	ProgramID        uuid.UUID   `json:"program_id"`
	WeekNumber       int16       `json:"week_number"`
	DayIndex         int16       `json:"day_index"`
	Name             string      `json:"name"`
	Note             pgtype.Text `json:"note"`
	IsDeload         bool        `json:"is_deload"`
	EstimatedMinutes pgtype.Int2 `json:"estimated_minutes"`
}

func (q *Queries) CreateProgramWorkout(ctx context.Context, arg CreateProgramWorkoutParams) (ProgramWorkout, error) {
	row := q.db.QueryRow(ctx, createProgramWorkout,
		arg.ProgramID,
		arg.WeekNumber,
		arg.DayIndex,
		arg.Name,
		arg.Note,
		arg.IsDeload,
		arg.EstimatedMinutes,
	)
	var i ProgramWorkout
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.WeekNumber,
		&i.DayIndex,
		&i.Name,
		&i.Note,
		&i.IsDeload,
		&i.EstimatedMinutes,
	)
	return i, err
}

const createProgressionRule = `-- name: CreateProgressionRule :one
INSERT INTO progression_rule (org_id, name, type, params, is_system)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, name, type, params, is_system, created_at
`

type CreateProgressionRuleParams struct {
	OrgID    pgtype.UUID     `json:"org_id"`
	Name     string          `json:"name"`
	Type     ProgressionType `json:"type"`
	Params   []byte          `json:"params"`
	IsSystem bool            `json:"is_system"`
}

func (q *Queries) CreateProgressionRule(ctx context.Context, arg CreateProgressionRuleParams) (ProgressionRule, error) {
	row := q.db.QueryRow(ctx, createProgressionRule,
		arg.OrgID,
		arg.Name,
		arg.Type,
		arg.Params,
		arg.IsSystem,
	)
	var i ProgressionRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Params,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProgramExercise = `-- name: DeleteProgramExercise :exec
DELETE FROM program_exercise WHERE id = $1
`

func (q *Queries) DeleteProgramExercise(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProgramExercise, id)
	return err
}

const deleteProgramWorkout = `-- name: DeleteProgramWorkout :exec
DELETE FROM program_workout WHERE id = $1
`

func (q *Queries) DeleteProgramWorkout(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProgramWorkout, id)
	return err
}

const getProgramByID = `-- name: GetProgramByID :one
SELECT id, org_id, created_by, name, description, goal, level, total_weeks, days_per_week, status, is_shared, created_at, updated_at FROM program WHERE id = $1 AND org_id = $2
`

type GetProgramByIDParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) GetProgramByID(ctx context.Context, arg GetProgramByIDParams) (Program, error) {
	row := q.db.QueryRow(ctx, getProgramByID, arg.ID, arg.OrgID)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.Goal,
		&i.Level,
		&i.TotalWeeks,
		&i.DaysPerWeek,
		&i.Status,
		&i.IsShared,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProgramExerciseWithOrg = `-- name: GetProgramExerciseWithOrg :one
SELECT pe.id, pe.program_workout_id, pe.exercise_id, pe.order_index, pe.superset_group, pe.target_sets, pe.target_reps_min, pe.target_reps_max, pe.target_rpe, pe.target_pct_1rm, pe.rest_seconds, pe.tempo, pe.note, pe.progression_rule_id, p.org_id AS program_org_id
FROM program_exercise pe
JOIN program_workout pw ON pw.id = pe.program_workout_id
JOIN program p ON p.id = pw.program_id
WHERE pe.id = $1
`

type GetProgramExerciseWithOrgRow struct {
	ID                uuid.UUID   `json:"id"`
	ProgramWorkoutID  uuid.UUID   `json:"program_workout_id"`
	ExerciseID        uuid.UUID   `json:"exercise_id"`
	OrderIndex        int16       `json:"order_index"`
	SupersetGroup     pgtype.Int2 `json:"superset_group"`
	TargetSets        int16       `json:"target_sets"`
	TargetRepsMin     pgtype.Int2 `json:"target_reps_min"`
	TargetRepsMax     pgtype.Int2 `json:"target_reps_max"`
	TargetRpe         *float64    `json:"target_rpe"`
	TargetPct1rm      *float64    `json:"target_pct_1rm"`
	RestSeconds       int16       `json:"rest_seconds"`
	Tempo             pgtype.Text `json:"tempo"`
	Note              pgtype.Text `json:"note"`
	ProgressionRuleID pgtype.UUID `json:"progression_rule_id"`
	ProgramOrgID      uuid.UUID   `json:"program_org_id"`
}

func (q *Queries) GetProgramExerciseWithOrg(ctx context.Context, id uuid.UUID) (GetProgramExerciseWithOrgRow, error) {
	row := q.db.QueryRow(ctx, getProgramExerciseWithOrg, id)
	var i GetProgramExerciseWithOrgRow
	err := row.Scan(
		&i.ID,
		&i.ProgramWorkoutID,
		&i.ExerciseID,
		&i.OrderIndex,
		&i.SupersetGroup,
		&i.TargetSets,
		&i.TargetRepsMin,
		&i.TargetRepsMax,
		&i.TargetRpe,
		&i.TargetPct1rm,
		&i.RestSeconds,
		&i.Tempo,
		&i.Note,
		&i.ProgressionRuleID,
		&i.ProgramOrgID,
	)
	return i, err
}

const getProgramWorkoutWithOrg = `-- name: GetProgramWorkoutWithOrg :one
SELECT pw.id, pw.program_id, pw.week_number, pw.day_index, pw.name, pw.note, pw.is_deload, pw.estimated_minutes, p.org_id AS program_org_id
FROM program_workout pw
JOIN program p ON p.id = pw.program_id
WHERE pw.id = $1
`

type GetProgramWorkoutWithOrgRow struct {
	ID               uuid.UUID   `json:"id"`
	ProgramID        uuid.UUID   `json:"program_id"`
	WeekNumber       int16       `json:"week_number"`
	DayIndex         int16       `json:"day_index"`
	Name             string      `json:"name"`
	Note             pgtype.Text `json:"note"`
	IsDeload         bool        `json:"is_deload"`
	EstimatedMinutes pgtype.Int2 `json:"estimated_minutes"`
	ProgramOrgID     uuid.UUID   `json:"program_org_id"`
}

func (q *Queries) GetProgramWorkoutWithOrg(ctx context.Context, id uuid.UUID) (GetProgramWorkoutWithOrgRow, error) {
	row := q.db.QueryRow(ctx, getProgramWorkoutWithOrg, id)
	var i GetProgramWorkoutWithOrgRow
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.WeekNumber,
		&i.DayIndex,
		&i.Name,
		&i.Note,
		&i.IsDeload,
		&i.EstimatedMinutes,
		&i.ProgramOrgID,
	)
	return i, err
}

const getProgressionRuleByID = `-- name: GetProgressionRuleByID :one
SELECT id, org_id, name, type, params, is_system, created_at FROM progression_rule WHERE id = $1
`

func (q *Queries) GetProgressionRuleByID(ctx context.Context, id uuid.UUID) (ProgressionRule, error) {
	row := q.db.QueryRow(ctx, getProgressionRuleByID, id)
	var i ProgressionRule
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Type,
		&i.Params,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listProgramExercises = `-- name: ListProgramExercises :many
SELECT id, program_workout_id, exercise_id, order_index, superset_group, target_sets, target_reps_min, target_reps_max, target_rpe, target_pct_1rm, rest_seconds, tempo, note, progression_rule_id FROM program_exercise WHERE program_workout_id = $1 ORDER BY order_index
`

func (q *Queries) ListProgramExercises(ctx context.Context, programWorkoutID uuid.UUID) ([]ProgramExercise, error) {
	rows, err := q.db.Query(ctx, listProgramExercises, programWorkoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgramExercise{}
	for rows.Next() {
		var i ProgramExercise
		if err := rows.Scan(
			&i.ID,
			&i.ProgramWorkoutID,
			&i.ExerciseID,
			&i.OrderIndex,
			&i.SupersetGroup,
			&i.TargetSets,
			&i.TargetRepsMin,
			&i.TargetRepsMax,
			&i.TargetRpe,
			&i.TargetPct1rm,
			&i.RestSeconds,
			&i.Tempo,
			&i.Note,
			&i.ProgressionRuleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramWorkouts = `-- name: ListProgramWorkouts :many
SELECT id, program_id, week_number, day_index, name, note, is_deload, estimated_minutes FROM program_workout WHERE program_id = $1 ORDER BY week_number, day_index
`

func (q *Queries) ListProgramWorkouts(ctx context.Context, programID uuid.UUID) ([]ProgramWorkout, error) {
	rows, err := q.db.Query(ctx, listProgramWorkouts, programID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgramWorkout{}
	for rows.Next() {
		var i ProgramWorkout
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.WeekNumber,
			&i.DayIndex,
			&i.Name,
			&i.Note,
			&i.IsDeload,
			&i.EstimatedMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsByOrg = `-- name: ListProgramsByOrg :many
SELECT id, org_id, created_by, name, description, goal, level, total_weeks, days_per_week, status, is_shared, created_at, updated_at FROM program
WHERE org_id = $1
  AND ($2::program_status IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListProgramsByOrgParams struct {
	OrgID       uuid.UUID         `json:"org_id"`
	Status      NullProgramStatus `json:"status"`
	OffsetCount int32             `json:"offset_count"`
	LimitCount  int32             `json:"limit_count"`
}

func (q *Queries) ListProgramsByOrg(ctx context.Context, arg ListProgramsByOrgParams) ([]Program, error) {
	rows, err := q.db.Query(ctx, listProgramsByOrg,
		arg.OrgID,
		arg.Status,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Program{}
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.Goal,
			&i.Level,
			&i.TotalWeeks,
			&i.DaysPerWeek,
			&i.Status,
			&i.IsShared,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgressionRules = `-- name: ListProgressionRules :many
SELECT id, org_id, name, type, params, is_system, created_at FROM progression_rule
WHERE org_id IS NULL OR org_id = $1
ORDER BY is_system DESC, name
`

func (q *Queries) ListProgressionRules(ctx context.Context, orgID pgtype.UUID) ([]ProgressionRule, error) {
	rows, err := q.db.Query(ctx, listProgressionRules, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgressionRule{}
	for rows.Next() {
		var i ProgressionRule
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Type,
			&i.Params,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProgramStatus = `-- name: SetProgramStatus :one
UPDATE program SET status = $3 WHERE id = $1 AND org_id = $2 RETURNING id, org_id, created_by, name, description, goal, level, total_weeks, days_per_week, status, is_shared, created_at, updated_at
`

type SetProgramStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	OrgID  uuid.UUID     `json:"org_id"`
	Status ProgramStatus `json:"status"`
}

func (q *Queries) SetProgramStatus(ctx context.Context, arg SetProgramStatusParams) (Program, error) {
	row := q.db.QueryRow(ctx, setProgramStatus, arg.ID, arg.OrgID, arg.Status)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.Goal,
		&i.Level,
		&i.TotalWeeks,
		&i.DaysPerWeek,
		&i.Status,
		&i.IsShared,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProgram = `-- name: UpdateProgram :one
UPDATE program SET
  name = $3, description = $4, goal = $5, level = $6, total_weeks = $7, days_per_week = $8
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, created_by, name, description, goal, level, total_weeks, days_per_week, status, is_shared, created_at, updated_at
`

type UpdateProgramParams struct {
	ID          uuid.UUID       `json:"id"`
	OrgID       uuid.UUID       `json:"org_id"`
	Name        string          `json:"name"`
	Description pgtype.Text     `json:"description"`
	Goal        TrainingGoal    `json:"goal"`
	Level       ExperienceLevel `json:"level"`
	TotalWeeks  int16           `json:"total_weeks"`
	DaysPerWeek int16           `json:"days_per_week"`
}

func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) (Program, error) {
	row := q.db.QueryRow(ctx, updateProgram,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Goal,
		arg.Level,
		arg.TotalWeeks,
		arg.DaysPerWeek,
	)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.Goal,
		&i.Level,
		&i.TotalWeeks,
		&i.DaysPerWeek,
		&i.Status,
		&i.IsShared,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProgramExercise = `-- name: UpdateProgramExercise :one
UPDATE program_exercise SET
  order_index = $2, superset_group = $3, target_sets = $4, target_reps_min = $5,
  target_reps_max = $6, target_rpe = $7, target_pct_1rm = $8, rest_seconds = $9,
  tempo = $10, note = $11, progression_rule_id = $12
WHERE id = $1
RETURNING id, program_workout_id, exercise_id, order_index, superset_group, target_sets, target_reps_min, target_reps_max, target_rpe, target_pct_1rm, rest_seconds, tempo, note, progression_rule_id
`

type UpdateProgramExerciseParams struct {
	ID                uuid.UUID   `json:"id"`
	OrderIndex        int16       `json:"order_index"`
	SupersetGroup     pgtype.Int2 `json:"superset_group"`
	TargetSets        int16       `json:"target_sets"`
	TargetRepsMin     pgtype.Int2 `json:"target_reps_min"`
	TargetRepsMax     pgtype.Int2 `json:"target_reps_max"`
	TargetRpe         *float64    `json:"target_rpe"`
	TargetPct1rm      *float64    `json:"target_pct_1rm"`
	RestSeconds       int16       `json:"rest_seconds"`
	Tempo             pgtype.Text `json:"tempo"`
	Note              pgtype.Text `json:"note"`
	ProgressionRuleID pgtype.UUID `json:"progression_rule_id"`
}

func (q *Queries) UpdateProgramExercise(ctx context.Context, arg UpdateProgramExerciseParams) (ProgramExercise, error) {
	row := q.db.QueryRow(ctx, updateProgramExercise,
		arg.ID,
		arg.OrderIndex,
		arg.SupersetGroup,
		arg.TargetSets,
		arg.TargetRepsMin,
		arg.TargetRepsMax,
		arg.TargetRpe,
		arg.TargetPct1rm,
		arg.RestSeconds,
		arg.Tempo,
		arg.Note,
		arg.ProgressionRuleID,
	)
	var i ProgramExercise
	err := row.Scan(
		&i.ID,
		&i.ProgramWorkoutID,
		&i.ExerciseID,
		&i.OrderIndex,
		&i.SupersetGroup,
		&i.TargetSets,
		&i.TargetRepsMin,
		&i.TargetRepsMax,
		&i.TargetRpe,
		&i.TargetPct1rm,
		&i.RestSeconds,
		&i.Tempo,
		&i.Note,
		&i.ProgressionRuleID,
	)
	return i, err
}

const updateProgramWorkout = `-- name: UpdateProgramWorkout :one
UPDATE program_workout SET
  name = $2, note = $3, is_deload = $4, estimated_minutes = $5
WHERE id = $1
RETURNING id, program_id, week_number, day_index, name, note, is_deload, estimated_minutes
`

type UpdateProgramWorkoutParams struct {
	ID               uuid.UUID   `json:"id"`
	Name             string      `json:"name"`
	Note             pgtype.Text `json:"note"`
	IsDeload         bool        `json:"is_deload"`
	EstimatedMinutes pgtype.Int2 `json:"estimated_minutes"`
}

func (q *Queries) UpdateProgramWorkout(ctx context.Context, arg UpdateProgramWorkoutParams) (ProgramWorkout, error) {
	row := q.db.QueryRow(ctx, updateProgramWorkout,
		arg.ID,
		arg.Name,
		arg.Note,
		arg.IsDeload,
		arg.EstimatedMinutes,
	)
	var i ProgramWorkout
	err := row.Scan(
		&i.ID,
		&i.ProgramID,
		&i.WeekNumber,
		&i.DayIndex,
		&i.Name,
		&i.Note,
		&i.IsDeload,
		&i.EstimatedMinutes,
	)
	return i, err
}
