// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelAssignment(ctx context.Context, arg CancelAssignmentParams) (Assignment, error)
	CountActiveHabitsForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountAssignedWorkoutsInRange(ctx context.Context, arg CountAssignedWorkoutsInRangeParams) (int64, error)
	CountCompletedHabitLogsForDate(ctx context.Context, arg CountCompletedHabitLogsForDateParams) (int64, error)
	CountCompletedHabitLogsSince(ctx context.Context, arg CountCompletedHabitLogsSinceParams) (int64, error)
	CountCompletedSessionsOnDate(ctx context.Context, arg CountCompletedSessionsOnDateParams) (int64, error)
	CountCompletedSessionsSince(ctx context.Context, arg CountCompletedSessionsSinceParams) (int64, error)
	CreateAISuggestion(ctx context.Context, arg CreateAISuggestionParams) (AiSuggestion, error)
	CreateAssignedExercise(ctx context.Context, arg CreateAssignedExerciseParams) (AssignedExercise, error)
	CreateAssignedWorkout(ctx context.Context, arg CreateAssignedWorkoutParams) (AssignedWorkout, error)
	CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error)
	CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateProgram(ctx context.Context, arg CreateProgramParams) (Program, error)
	CreateProgramExercise(ctx context.Context, arg CreateProgramExerciseParams) (ProgramExercise, error)
	CreateProgramWorkout(ctx context.Context, arg CreateProgramWorkoutParams) (ProgramWorkout, error)
	CreateProgressionRule(ctx context.Context, arg CreateProgressionRuleParams) (ProgressionRule, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error)
	CreateXPEvent(ctx context.Context, arg CreateXPEventParams) (XpEvent, error)
	DeactivateExercise(ctx context.Context, arg DeactivateExerciseParams) (int64, error)
	DeleteProgramExercise(ctx context.Context, id uuid.UUID) error
	DeleteProgramWorkout(ctx context.Context, id uuid.UUID) error
	// La proxima vez que este ejercicio aparece en el plan, saltando el dia que
	// se acaba de entrenar (excluded_workout_id) y los ya completados.
	FindNextAssignedExercise(ctx context.Context, arg FindNextAssignedExerciseParams) (AssignedExercise, error)
	GetAISuggestionByID(ctx context.Context, arg GetAISuggestionByIDParams) (AiSuggestion, error)
	GetActiveAssignmentByClient(ctx context.Context, clientUserID uuid.UUID) (Assignment, error)
	GetActiveClientHabit(ctx context.Context, arg GetActiveClientHabitParams) (ClientHabit, error)
	GetActiveMembershipByUser(ctx context.Context, userID uuid.UUID) (Membership, error)
	GetAssignmentByID(ctx context.Context, id uuid.UUID) (Assignment, error)
	GetClientHabitOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetClientProfile(ctx context.Context, userID uuid.UUID) (ClientProfile, error)
	GetExerciseByID(ctx context.Context, id uuid.UUID) (Exercise, error)
	GetHabitByID(ctx context.Context, id uuid.UUID) (Habit, error)
	GetOrgMembership(ctx context.Context, arg GetOrgMembershipParams) (Membership, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationByJoinCode(ctx context.Context, joinCode string) (Organization, error)
	GetPersonalRecord(ctx context.Context, arg GetPersonalRecordParams) (PersonalRecord, error)
	GetProgramByID(ctx context.Context, arg GetProgramByIDParams) (Program, error)
	GetProgramExerciseWithOrg(ctx context.Context, id uuid.UUID) (GetProgramExerciseWithOrgRow, error)
	GetProgramWorkoutWithOrg(ctx context.Context, id uuid.UUID) (GetProgramWorkoutWithOrgRow, error)
	GetProgressionRuleByID(ctx context.Context, id uuid.UUID) (ProgressionRule, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserAchievement(ctx context.Context, arg GetUserAchievementParams) (UserAchievement, error)
	GetUserByEmail(ctx context.Context, email string) (AppUser, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (AppUser, error)
	GetUserStats(ctx context.Context, userID uuid.UUID) (UserStat, error)
	GetUserStreak(ctx context.Context, arg GetUserStreakParams) (UserStreak, error)
	GetWorkoutAssignmentID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	LinkCoachClient(ctx context.Context, arg LinkCoachClientParams) error
	ListAchievements(ctx context.Context) ([]Achievement, error)
	ListActiveAssignmentsForWorker(ctx context.Context) ([]ListActiveAssignmentsForWorkerRow, error)
	ListAssignedExercises(ctx context.Context, assignedWorkoutID uuid.UUID) ([]AssignedExercise, error)
	ListAssignedWorkouts(ctx context.Context, assignmentID uuid.UUID) ([]AssignedWorkout, error)
	ListBodyMetrics(ctx context.Context, arg ListBodyMetricsParams) ([]BodyMetric, error)
	ListCoachClients(ctx context.Context, arg ListCoachClientsParams) ([]ListCoachClientsRow, error)
	ListExercises(ctx context.Context, arg ListExercisesParams) ([]Exercise, error)
	ListHabitLogsForDate(ctx context.Context, arg ListHabitLogsForDateParams) ([]HabitLog, error)
	ListHabits(ctx context.Context, orgID pgtype.UUID) ([]Habit, error)
	ListMyHabits(ctx context.Context, userID uuid.UUID) ([]ListMyHabitsRow, error)
	ListOrgMembers(ctx context.Context, orgID uuid.UUID) ([]ListOrgMembersRow, error)
	ListPendingSuggestionsForCoach(ctx context.Context, arg ListPendingSuggestionsForCoachParams) ([]ListPendingSuggestionsForCoachRow, error)
	ListPersonalRecords(ctx context.Context, arg ListPersonalRecordsParams) ([]PersonalRecord, error)
	ListProgramExercises(ctx context.Context, programWorkoutID uuid.UUID) ([]ProgramExercise, error)
	ListProgramWorkouts(ctx context.Context, programID uuid.UUID) ([]ProgramWorkout, error)
	ListProgramsByOrg(ctx context.Context, arg ListProgramsByOrgParams) ([]Program, error)
	ListProgressionRules(ctx context.Context, orgID pgtype.UUID) ([]ProgressionRule, error)
	ListRecentWorkingSets(ctx context.Context, arg ListRecentWorkingSetsParams) ([]ListRecentWorkingSetsRow, error)
	ListSessionsForVolume(ctx context.Context, arg ListSessionsForVolumeParams) ([]ListSessionsForVolumeRow, error)
	ListSetLogsForExercise(ctx context.Context, arg ListSetLogsForExerciseParams) ([]SetLog, error)
	ListUserAchievements(ctx context.Context, userID uuid.UUID) ([]ListUserAchievementsRow, error)
	ListUserStreaks(ctx context.Context, userID uuid.UUID) ([]UserStreak, error)
	MarkAISuggestionApplied(ctx context.Context, arg MarkAISuggestionAppliedParams) error
	MarkAssignedWorkoutCompleted(ctx context.Context, id uuid.UUID) error
	ReviewAISuggestion(ctx context.Context, arg ReviewAISuggestionParams) (AiSuggestion, error)
	RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error
	SetProgramStatus(ctx context.Context, arg SetProgramStatusParams) (Program, error)
	SubscribeHabit(ctx context.Context, arg SubscribeHabitParams) (ClientHabit, error)
	TouchUserLogin(ctx context.Context, id uuid.UUID) error
	UnsubscribeHabit(ctx context.Context, arg UnsubscribeHabitParams) error
	UpdateAssignedExerciseTargets(ctx context.Context, arg UpdateAssignedExerciseTargetsParams) (AssignedExercise, error)
	UpdateExercise(ctx context.Context, arg UpdateExerciseParams) (Exercise, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (Membership, error)
	UpdateProgram(ctx context.Context, arg UpdateProgramParams) (Program, error)
	UpdateProgramExercise(ctx context.Context, arg UpdateProgramExerciseParams) (ProgramExercise, error)
	UpdateProgramWorkout(ctx context.Context, arg UpdateProgramWorkoutParams) (ProgramWorkout, error)
	UpsertBodyMetric(ctx context.Context, arg UpsertBodyMetricParams) (BodyMetric, error)
	UpsertClientProfile(ctx context.Context, arg UpsertClientProfileParams) (ClientProfile, error)
	UpsertHabitLog(ctx context.Context, arg UpsertHabitLogParams) (HabitLog, error)
	UpsertPersonalRecord(ctx context.Context, arg UpsertPersonalRecordParams) (PersonalRecord, error)
	UpsertSessionExercise(ctx context.Context, arg UpsertSessionExerciseParams) (SessionExercise, error)
	UpsertSetLog(ctx context.Context, arg UpsertSetLogParams) (SetLog, error)
	UpsertUserAchievement(ctx context.Context, arg UpsertUserAchievementParams) (UserAchievement, error)
	UpsertUserStats(ctx context.Context, arg UpsertUserStatsParams) (UserStat, error)
	UpsertUserStreak(ctx context.Context, arg UpsertUserStreakParams) (UserStreak, error)
	UpsertWorkoutSession(ctx context.Context, arg UpsertWorkoutSessionParams) (WorkoutSession, error)
}

var _ Querier = (*Queries)(nil)
