// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCompletedSessionsOnDate = `-- name: CountCompletedSessionsOnDate :one
SELECT count(*) FROM workout_session
WHERE user_id = $1 AND status = 'completed' AND started_at::date = $2::date
`

type CountCompletedSessionsOnDateParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 time.Time `json:"column_2"`
}

func (q *Queries) CountCompletedSessionsOnDate(ctx context.Context, arg CountCompletedSessionsOnDateParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedSessionsOnDate, arg.UserID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPersonalRecord = `-- name: GetPersonalRecord :one
SELECT id, user_id, exercise_id, type, value, set_log_id, achieved_at FROM personal_record WHERE user_id = $1 AND exercise_id = $2 AND type = $3
`

type GetPersonalRecordParams struct {
	UserID     uuid.UUID  `json:"user_id"`
	ExerciseID uuid.UUID  `json:"exercise_id"`
	Type       RecordType `json:"type"`
}

func (q *Queries) GetPersonalRecord(ctx context.Context, arg GetPersonalRecordParams) (PersonalRecord, error) {
	row := q.db.QueryRow(ctx, getPersonalRecord, arg.UserID, arg.ExerciseID, arg.Type)
	var i PersonalRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseID,
		&i.Type,
		&i.Value,
		&i.SetLogID,
		&i.AchievedAt,
	)
	return i, err
}

const listPersonalRecordsForExercise = `-- name: ListPersonalRecordsForExercise :many
SELECT id, user_id, exercise_id, type, value, set_log_id, achieved_at FROM personal_record WHERE user_id = $1 AND exercise_id = $2
`

type ListPersonalRecordsForExerciseParams struct {
	UserID     uuid.UUID `json:"user_id"`
	ExerciseID uuid.UUID `json:"exercise_id"`
}

// Los 4 tipos de record de un ejercicio en una sola ida a la base: antes se
// consultaba uno por uno por cada serie de trabajo.
func (q *Queries) ListPersonalRecordsForExercise(ctx context.Context, arg ListPersonalRecordsForExerciseParams) ([]PersonalRecord, error) {
	rows, err := q.db.Query(ctx, listPersonalRecordsForExercise, arg.UserID, arg.ExerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PersonalRecord{}
	for rows.Next() {
		var i PersonalRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseID,
			&i.Type,
			&i.Value,
			&i.SetLogID,
			&i.AchievedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPersonalRecord = `-- name: UpsertPersonalRecord :one
INSERT INTO personal_record (user_id, exercise_id, type, value, set_log_id, achieved_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, exercise_id, type) DO UPDATE SET
  value = EXCLUDED.value, set_log_id = EXCLUDED.set_log_id, achieved_at = EXCLUDED.achieved_at
RETURNING id, user_id, exercise_id, type, value, set_log_id, achieved_at
`

type UpsertPersonalRecordParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	ExerciseID uuid.UUID   `json:"exercise_id"`
	Type       RecordType  `json:"type"`
	Value      float64     `json:"value"`
	SetLogID   pgtype.Int8 `json:"set_log_id"`
	AchievedAt time.Time   `json:"achieved_at"`
}

func (q *Queries) UpsertPersonalRecord(ctx context.Context, arg UpsertPersonalRecordParams) (PersonalRecord, error) {
	row := q.db.QueryRow(ctx, upsertPersonalRecord,
		arg.UserID,
		arg.ExerciseID,
		arg.Type,
		arg.Value,
		arg.SetLogID,
		arg.AchievedAt,
	)
	var i PersonalRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExerciseID,
		&i.Type,
		&i.Value,
		&i.SetLogID,
		&i.AchievedAt,
	)
	return i, err
}

const upsertSessionExercise = `-- name: UpsertSessionExercise :one
INSERT INTO session_exercise (session_id, exercise_id, assigned_exercise_id, order_index, superset_group, note)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (session_id, order_index) DO UPDATE SET
  exercise_id = EXCLUDED.exercise_id, assigned_exercise_id = EXCLUDED.assigned_exercise_id,
  superset_group = EXCLUDED.superset_group, note = EXCLUDED.note
RETURNING id, session_id, exercise_id, assigned_exercise_id, order_index, superset_group, note
`

type UpsertSessionExerciseParams struct {
	SessionID          uuid.UUID   `json:"session_id"`
	ExerciseID         uuid.UUID   `json:"exercise_id"`
	AssignedExerciseID pgtype.UUID `json:"assigned_exercise_id"`
	OrderIndex         int16       `json:"order_index"`
	SupersetGroup      pgtype.Int2 `json:"superset_group"`
	Note               pgtype.Text `json:"note"`
}

func (q *Queries) UpsertSessionExercise(ctx context.Context, arg UpsertSessionExerciseParams) (SessionExercise, error) {
	row := q.db.QueryRow(ctx, upsertSessionExercise,
		arg.SessionID,
		arg.ExerciseID,
		arg.AssignedExerciseID,
		arg.OrderIndex,
		arg.SupersetGroup,
		arg.Note,
	)
	var i SessionExercise
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ExerciseID,
		&i.AssignedExerciseID,
		&i.OrderIndex,
		&i.SupersetGroup,
		&i.Note,
	)
	return i, err
}

const upsertSetLog = `-- name: UpsertSetLog :one
INSERT INTO set_log (
  client_local_id, session_exercise_id, user_id, exercise_id, set_number, type,
  weight_kg, reps, rpe, rir, duration_seconds, distance_m, rest_taken_seconds,
  is_completed, performed_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (user_id, client_local_id) DO UPDATE SET
  weight_kg = EXCLUDED.weight_kg, reps = EXCLUDED.reps, rpe = EXCLUDED.rpe, rir = EXCLUDED.rir,
  duration_seconds = EXCLUDED.duration_seconds, distance_m = EXCLUDED.distance_m,
  rest_taken_seconds = EXCLUDED.rest_taken_seconds, is_completed = EXCLUDED.is_completed
RETURNING id, client_local_id, session_exercise_id, user_id, exercise_id, set_number, type, weight_kg, reps, rpe, rir, duration_seconds, distance_m, rest_taken_seconds, is_completed, performed_at
`

type UpsertSetLogParams struct {
	ClientLocalID     uuid.UUID   `json:"client_local_id"`
	SessionExerciseID uuid.UUID   `json:"session_exercise_id"`
	UserID            uuid.UUID   `json:"user_id"`
	ExerciseID        uuid.UUID   `json:"exercise_id"`
	SetNumber         int16       `json:"set_number"`
	Type              SetType     `json:"type"`
	WeightKg          *float64    `json:"weight_kg"`
	Reps              pgtype.Int2 `json:"reps"`
	Rpe               *float64    `json:"rpe"`
	Rir               pgtype.Int2 `json:"rir"`
	DurationSeconds   pgtype.Int4 `json:"duration_seconds"`
	DistanceM         *float64    `json:"distance_m"`
	RestTakenSeconds  pgtype.Int4 `json:"rest_taken_seconds"`
	IsCompleted       bool        `json:"is_completed"`
	PerformedAt       time.Time   `json:"performed_at"`
}

func (q *Queries) UpsertSetLog(ctx context.Context, arg UpsertSetLogParams) (SetLog, error) {
	row := q.db.QueryRow(ctx, upsertSetLog,
		arg.ClientLocalID,
		arg.SessionExerciseID,
		arg.UserID,
		arg.ExerciseID,
		arg.SetNumber,
		arg.Type,
		arg.WeightKg,
		arg.Reps,
		arg.Rpe,
		arg.Rir,
		arg.DurationSeconds,
		arg.DistanceM,
		arg.RestTakenSeconds,
		arg.IsCompleted,
		arg.PerformedAt,
	)
	var i SetLog
	err := row.Scan(
		&i.ID,
		&i.ClientLocalID,
		&i.SessionExerciseID,
		&i.UserID,
		&i.ExerciseID,
		&i.SetNumber,
		&i.Type,
		&i.WeightKg,
		&i.Reps,
		&i.Rpe,
		&i.Rir,
		&i.DurationSeconds,
		&i.DistanceM,
		&i.RestTakenSeconds,
		&i.IsCompleted,
		&i.PerformedAt,
	)
	return i, err
}

const upsertWorkoutSession = `-- name: UpsertWorkoutSession :one
INSERT INTO workout_session (
  client_local_id, user_id, org_id, assigned_workout_id, name, status,
  started_at, ended_at, duration_seconds, total_volume_kg, perceived_effort, mood, notes
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (user_id, client_local_id) DO UPDATE SET
  status = EXCLUDED.status, ended_at = EXCLUDED.ended_at, duration_seconds = EXCLUDED.duration_seconds,
  total_volume_kg = EXCLUDED.total_volume_kg, perceived_effort = EXCLUDED.perceived_effort,
  mood = EXCLUDED.mood, notes = EXCLUDED.notes, synced_at = now()
RETURNING id, client_local_id, user_id, org_id, assigned_workout_id, name, status, started_at, ended_at, duration_seconds, total_volume_kg, perceived_effort, mood, notes, synced_at, created_at, (xmax = 0) AS inserted
`

type UpsertWorkoutSessionParams struct {
	ClientLocalID     uuid.UUID     `json:"client_local_id"`
	UserID            uuid.UUID     `json:"user_id"`
	OrgID             pgtype.UUID   `json:"org_id"`
	AssignedWorkoutID pgtype.UUID   `json:"assigned_workout_id"`
	Name              string        `json:"name"`
	Status            SessionStatus `json:"status"`
	StartedAt         time.Time     `json:"started_at"`
	EndedAt           *time.Time    `json:"ended_at"`
	DurationSeconds   pgtype.Int4   `json:"duration_seconds"`
	TotalVolumeKg     float64       `json:"total_volume_kg"`
	PerceivedEffort   pgtype.Int2   `json:"perceived_effort"`
	Mood              pgtype.Int2   `json:"mood"`
	Notes             pgtype.Text   `json:"notes"`
}

type UpsertWorkoutSessionRow struct {
	ID                uuid.UUID     `json:"id"`
	ClientLocalID     uuid.UUID     `json:"client_local_id"`
	UserID            uuid.UUID     `json:"user_id"`
	OrgID             pgtype.UUID   `json:"org_id"`
	AssignedWorkoutID pgtype.UUID   `json:"assigned_workout_id"`
	Name              string        `json:"name"`
	Status            SessionStatus `json:"status"`
	StartedAt         time.Time     `json:"started_at"`
	EndedAt           *time.Time    `json:"ended_at"`
	DurationSeconds   pgtype.Int4   `json:"duration_seconds"`
	TotalVolumeKg     float64       `json:"total_volume_kg"`
	PerceivedEffort   pgtype.Int2   `json:"perceived_effort"`
	Mood              pgtype.Int2   `json:"mood"`
	Notes             pgtype.Text   `json:"notes"`
	SyncedAt          time.Time     `json:"synced_at"`
	CreatedAt         time.Time     `json:"created_at"`
	Inserted          bool          `json:"inserted"`
}

// xmax = 0 distingue una fila recien insertada de una que el upsert
// actualizo: es como Postgres deja ver si el ON CONFLICT se disparo. Sin
// esto, reenviar el mismo lote vuelve a otorgar XP, racha y logros.
func (q *Queries) UpsertWorkoutSession(ctx context.Context, arg UpsertWorkoutSessionParams) (UpsertWorkoutSessionRow, error) {
	row := q.db.QueryRow(ctx, upsertWorkoutSession,
		arg.ClientLocalID,
		arg.UserID,
		arg.OrgID,
		arg.AssignedWorkoutID,
		arg.Name,
		arg.Status,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationSeconds,
		arg.TotalVolumeKg,
		arg.PerceivedEffort,
		arg.Mood,
		arg.Notes,
	)
	var i UpsertWorkoutSessionRow
	err := row.Scan(
		&i.ID,
		&i.ClientLocalID,
		&i.UserID,
		&i.OrgID,
		&i.AssignedWorkoutID,
		&i.Name,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.TotalVolumeKg,
		&i.PerceivedEffort,
		&i.Mood,
		&i.Notes,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.Inserted,
	)
	return i, err
}
